// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _filter_c_engine_HH_
#define _filter_c_engine_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct filter_c_engine : public sc_module {
    // Port declarations 23
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<24> > xn_0_V;
    sc_in< sc_lv<16> > coeff_gain_V_read;
    sc_in< sc_lv<16> > coeff_b0_V_read;
    sc_in< sc_lv<16> > coeff_b1_V_read;
    sc_in< sc_lv<16> > coeff_b2_V_read;
    sc_in< sc_lv<16> > coeff_a1_n_V_read;
    sc_in< sc_lv<16> > coeff_a2_n_V_read;
    sc_in< sc_lv<24> > buf_yn_1_V_read;
    sc_in< sc_lv<24> > buf_yn_2_V_read;
    sc_in< sc_lv<24> > buf_xn_1_V_read;
    sc_in< sc_lv<24> > buf_xn_2_V_read;
    sc_out< sc_lv<24> > ap_return_0;
    sc_out< sc_lv<24> > ap_return_1;
    sc_out< sc_lv<24> > ap_return_2;
    sc_out< sc_lv<24> > ap_return_3;
    sc_out< sc_lv<24> > ap_return_4;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    filter_c_engine(sc_module_name name);
    SC_HAS_PROCESS(filter_c_engine);

    ~filter_c_engine();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_lv<40> > grp_fu_194_p2;
    sc_signal< sc_lv<41> > reg_171;
    sc_signal< sc_lv<42> > grp_fu_164_p2;
    sc_signal< sc_lv<41> > reg_178;
    sc_signal< sc_lv<24> > grp_fu_444_p3;
    sc_signal< sc_lv<24> > xn_0_scaled_V_reg_188;
    sc_signal< sc_lv<41> > reg_191;
    sc_signal< sc_lv<24> > p_Val2_10_reg_808;
    sc_signal< sc_lv<1> > tmp_17_reg_813;
    sc_signal< sc_lv<1> > signbit_1_reg_818;
    sc_signal< sc_lv<1> > Range2_all_ones_1_fu_604_p2;
    sc_signal< sc_lv<1> > Range2_all_ones_1_reg_824;
    sc_signal< sc_lv<1> > Range1_all_ones_1_fu_588_p2;
    sc_signal< sc_lv<1> > Range1_all_ones_1_reg_829;
    sc_signal< sc_lv<1> > Range1_all_zeros_1_fu_610_p2;
    sc_signal< sc_lv<1> > Range1_all_zeros_1_reg_836;
    sc_signal< sc_lv<42> > grp_fu_164_p0;
    sc_signal< sc_lv<41> > tmp_17_cast_fu_487_p1;
    sc_signal< sc_lv<41> > tmp_20_cast_cast_fu_522_p1;
    sc_signal< sc_lv<42> > tmp4_cast_fu_565_p1;
    sc_signal< sc_lv<42> > grp_fu_164_p1;
    sc_signal< sc_lv<24> > tmp_s_fu_616_p1;
    sc_signal< sc_lv<41> > tmp_19_cast_fu_502_p1;
    sc_signal< sc_lv<41> > tmp_18_cast_fu_236_p1;
    sc_signal< sc_lv<41> > tmp_21_cast_cast_fu_537_p1;
    sc_signal< sc_lv<42> > p_Val2_8_cast_fu_560_p1;
    sc_signal< sc_lv<24> > tmp_8_fu_273_p1;
    sc_signal< sc_lv<24> > grp_fu_194_p0;
    sc_signal< sc_lv<40> > OP2_V_fu_241_p1;
    sc_signal< sc_lv<40> > OP1_V_1_fu_477_p1;
    sc_signal< sc_lv<40> > OP1_V_2_fu_468_p1;
    sc_signal< sc_lv<40> > OP1_V_3_fu_492_p1;
    sc_signal< sc_lv<40> > OP1_V_4_fu_512_p1;
    sc_signal< sc_lv<40> > OP1_V_5_fu_527_p1;
    sc_signal< sc_lv<16> > grp_fu_194_p1;
    sc_signal< sc_lv<40> > OP1_V_fu_507_p1;
    sc_signal< sc_lv<40> > OP2_V_1_fu_472_p1;
    sc_signal< sc_lv<40> > OP2_V_2_fu_482_p1;
    sc_signal< sc_lv<40> > OP2_V_3_fu_497_p1;
    sc_signal< sc_lv<40> > OP2_V_4_fu_517_p1;
    sc_signal< sc_lv<40> > OP2_V_5_fu_532_p1;
    sc_signal< sc_lv<24> > grp_fu_228_p1;
    sc_signal< sc_lv<40> > tmp_18_cast_fu_236_p0;
    sc_signal< sc_lv<1> > grp_fu_228_p3;
    sc_signal< sc_lv<1> > Range2_all_ones_fu_332_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_378_p2;
    sc_signal< sc_lv<4> > tmp_2_fu_306_p4;
    sc_signal< sc_lv<3> > tmp_1_fu_322_p4;
    sc_signal< sc_lv<1> > carry_fu_358_p2;
    sc_signal< sc_lv<1> > p_41_i_fu_292_p2;
    sc_signal< sc_lv<1> > Range1_all_ones_fu_316_p2;
    sc_signal< sc_lv<1> > deleted_zeros_fu_364_p3;
    sc_signal< sc_lv<1> > tmp_13_fu_278_p3;
    sc_signal< sc_lv<1> > grp_fu_286_p2;
    sc_signal< sc_lv<1> > Range1_all_zeros_fu_338_p2;
    sc_signal< sc_lv<1> > deleted_ones_fu_344_p3;
    sc_signal< sc_lv<1> > tmp_15_fu_298_p3;
    sc_signal< sc_lv<1> > p_38_i_fu_402_p2;
    sc_signal< sc_lv<1> > brmerge40_demorgan_i_fu_372_p2;
    sc_signal< sc_lv<1> > signbit_fu_265_p3;
    sc_signal< sc_lv<1> > tmp1_fu_414_p2;
    sc_signal< sc_lv<1> > p_not_i_fu_352_p2;
    sc_signal< sc_lv<1> > tmp1_demorgan_fu_384_p2;
    sc_signal< sc_lv<1> > brmerge_i_fu_408_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_390_p2;
    sc_signal< sc_lv<1> > underflow_fu_396_p2;
    sc_signal< sc_lv<1> > overflow_fu_420_p2;
    sc_signal< sc_lv<1> > tmp2_fu_426_p2;
    sc_signal< sc_lv<1> > grp_fu_444_p0;
    sc_signal< sc_lv<1> > underflow_not_fu_438_p2;
    sc_signal< sc_lv<1> > underflow_1_not_fu_735_p2;
    sc_signal< sc_lv<24> > grp_fu_741_p3;
    sc_signal< sc_lv<24> > grp_fu_452_p3;
    sc_signal< sc_lv<1> > grp_fu_452_p0;
    sc_signal< sc_lv<1> > underflow_1_fu_718_p2;
    sc_signal< sc_lv<24> > grp_fu_452_p2;
    sc_signal< sc_lv<24> > OP1_V_2_fu_468_p0;
    sc_signal< sc_lv<40> > tmp_17_cast_fu_487_p0;
    sc_signal< sc_lv<24> > OP1_V_4_fu_512_p0;
    sc_signal< sc_lv<40> > tmp_20_cast_cast_fu_522_p0;
    sc_signal< sc_lv<41> > p_Val2_10_fu_542_p1;
    sc_signal< sc_lv<41> > tmp_17_fu_552_p1;
    sc_signal< sc_lv<41> > p_Val2_8_cast_fu_560_p0;
    sc_signal< sc_lv<41> > tmp4_cast_fu_565_p0;
    sc_signal< sc_lv<4> > tmp_11_fu_594_p4;
    sc_signal< sc_lv<3> > tmp_7_fu_578_p4;
    sc_signal< sc_lv<1> > tmp_fu_246_p3;
    sc_signal< sc_lv<1> > tmp_18_fu_640_p3;
    sc_signal< sc_lv<1> > carry_1_fu_634_p2;
    sc_signal< sc_lv<1> > tmp_20_fu_620_p3;
    sc_signal< sc_lv<1> > brmerge_i1_fu_706_p2;
    sc_signal< sc_lv<1> > tmp_12_fu_628_p2;
    sc_signal< sc_lv<1> > p_41_i1_fu_694_p2;
    sc_signal< sc_lv<1> > deleted_zeros_1_fu_648_p3;
    sc_signal< sc_lv<1> > p_38_i1_fu_672_p2;
    sc_signal< sc_lv<1> > brmerge40_demorgan_i_1_fu_700_p2;
    sc_signal< sc_lv<1> > tmp_10_fu_654_p2;
    sc_signal< sc_lv<1> > deleted_ones_1_fu_665_p3;
    sc_signal< sc_lv<1> > p_not_i1_fu_677_p2;
    sc_signal< sc_lv<1> > tmp5_demorgan_fu_683_p2;
    sc_signal< sc_lv<1> > tmp5_fu_712_p2;
    sc_signal< sc_lv<1> > overflow_1_fu_660_p2;
    sc_signal< sc_lv<1> > tmp6_fu_723_p2;
    sc_signal< sc_lv<1> > grp_fu_741_p0;
    sc_signal< sc_lv<1> > brmerge_i_i1_fu_729_p2;
    sc_signal< sc_lv<1> > brmerge_i_i_fu_432_p2;
    sc_signal< sc_lv<24> > grp_fu_741_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    sc_signal< sc_lv<24> > grp_fu_164_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<4> ap_ST_fsm_state5;
    static const sc_lv<4> ap_ST_fsm_state6;
    static const sc_lv<4> ap_ST_fsm_state7;
    static const sc_lv<4> ap_ST_fsm_state8;
    static const sc_lv<4> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_23;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<32> ap_const_lv32_25;
    static const sc_lv<3> ap_const_lv3_7;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<24> ap_const_lv24_800000;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_29;
    static const sc_lv<32> ap_const_lv32_26;
    static const sc_lv<24> ap_const_lv24_7FFFFF;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_OP1_V_1_fu_477_p1();
    void thread_OP1_V_2_fu_468_p0();
    void thread_OP1_V_2_fu_468_p1();
    void thread_OP1_V_3_fu_492_p1();
    void thread_OP1_V_4_fu_512_p0();
    void thread_OP1_V_4_fu_512_p1();
    void thread_OP1_V_5_fu_527_p1();
    void thread_OP1_V_fu_507_p1();
    void thread_OP2_V_1_fu_472_p1();
    void thread_OP2_V_2_fu_482_p1();
    void thread_OP2_V_3_fu_497_p1();
    void thread_OP2_V_4_fu_517_p1();
    void thread_OP2_V_5_fu_532_p1();
    void thread_OP2_V_fu_241_p1();
    void thread_Range1_all_ones_1_fu_588_p2();
    void thread_Range1_all_ones_fu_316_p2();
    void thread_Range1_all_zeros_1_fu_610_p2();
    void thread_Range1_all_zeros_fu_338_p2();
    void thread_Range2_all_ones_1_fu_604_p2();
    void thread_Range2_all_ones_fu_332_p2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_brmerge40_demorgan_i_1_fu_700_p2();
    void thread_brmerge40_demorgan_i_fu_372_p2();
    void thread_brmerge_i1_fu_706_p2();
    void thread_brmerge_i_fu_408_p2();
    void thread_brmerge_i_i1_fu_729_p2();
    void thread_brmerge_i_i_fu_432_p2();
    void thread_carry_1_fu_634_p2();
    void thread_carry_fu_358_p2();
    void thread_deleted_ones_1_fu_665_p3();
    void thread_deleted_ones_fu_344_p3();
    void thread_deleted_zeros_1_fu_648_p3();
    void thread_deleted_zeros_fu_364_p3();
    void thread_grp_fu_164_p0();
    void thread_grp_fu_164_p00();
    void thread_grp_fu_164_p1();
    void thread_grp_fu_164_p2();
    void thread_grp_fu_194_p0();
    void thread_grp_fu_194_p1();
    void thread_grp_fu_194_p2();
    void thread_grp_fu_228_p1();
    void thread_grp_fu_228_p3();
    void thread_grp_fu_286_p2();
    void thread_grp_fu_444_p0();
    void thread_grp_fu_444_p3();
    void thread_grp_fu_452_p0();
    void thread_grp_fu_452_p2();
    void thread_grp_fu_452_p3();
    void thread_grp_fu_741_p0();
    void thread_grp_fu_741_p2();
    void thread_grp_fu_741_p3();
    void thread_overflow_1_fu_660_p2();
    void thread_overflow_fu_420_p2();
    void thread_p_38_i1_fu_672_p2();
    void thread_p_38_i_fu_402_p2();
    void thread_p_41_i1_fu_694_p2();
    void thread_p_41_i_fu_292_p2();
    void thread_p_Val2_10_fu_542_p1();
    void thread_p_Val2_8_cast_fu_560_p0();
    void thread_p_Val2_8_cast_fu_560_p1();
    void thread_p_not_i1_fu_677_p2();
    void thread_p_not_i_fu_352_p2();
    void thread_signbit_fu_265_p3();
    void thread_tmp1_demorgan_fu_384_p2();
    void thread_tmp1_fu_414_p2();
    void thread_tmp2_fu_426_p2();
    void thread_tmp4_cast_fu_565_p0();
    void thread_tmp4_cast_fu_565_p1();
    void thread_tmp5_demorgan_fu_683_p2();
    void thread_tmp5_fu_712_p2();
    void thread_tmp6_fu_723_p2();
    void thread_tmp_10_fu_654_p2();
    void thread_tmp_11_fu_594_p4();
    void thread_tmp_12_fu_628_p2();
    void thread_tmp_13_fu_278_p3();
    void thread_tmp_15_fu_298_p3();
    void thread_tmp_17_cast_fu_487_p0();
    void thread_tmp_17_cast_fu_487_p1();
    void thread_tmp_17_fu_552_p1();
    void thread_tmp_18_cast_fu_236_p0();
    void thread_tmp_18_cast_fu_236_p1();
    void thread_tmp_18_fu_640_p3();
    void thread_tmp_19_cast_fu_502_p1();
    void thread_tmp_1_fu_322_p4();
    void thread_tmp_20_cast_cast_fu_522_p0();
    void thread_tmp_20_cast_cast_fu_522_p1();
    void thread_tmp_20_fu_620_p3();
    void thread_tmp_21_cast_cast_fu_537_p1();
    void thread_tmp_2_fu_306_p4();
    void thread_tmp_4_fu_378_p2();
    void thread_tmp_6_fu_390_p2();
    void thread_tmp_7_fu_578_p4();
    void thread_tmp_8_fu_273_p1();
    void thread_tmp_fu_246_p3();
    void thread_tmp_s_fu_616_p1();
    void thread_underflow_1_fu_718_p2();
    void thread_underflow_1_not_fu_735_p2();
    void thread_underflow_fu_396_p2();
    void thread_underflow_not_fu_438_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
