// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "getWeight.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic getWeight::ap_const_logic_1 = sc_dt::Log_1;
const bool getWeight::ap_const_boolean_1 = true;
const sc_lv<2> getWeight::ap_const_lv2_3 = "11";
const sc_lv<2> getWeight::ap_const_lv2_2 = "10";
const sc_lv<2> getWeight::ap_const_lv2_1 = "1";
const sc_lv<2> getWeight::ap_const_lv2_0 = "00";
const sc_lv<8> getWeight::ap_const_lv8_0 = "00000000";
const sc_logic getWeight::ap_const_logic_0 = sc_dt::Log_0;

getWeight::getWeight(sc_module_name name) : sc_module(name), mVcdFile(0) {
    network_top_mux_3eOg_U38 = new network_top_mux_3eOg<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,6,8>("network_top_mux_3eOg_U38");
    network_top_mux_3eOg_U38->din0(network_weights_weig);
    network_top_mux_3eOg_U38->din1(network_weights_weig_587);
    network_top_mux_3eOg_U38->din2(network_weights_weig_588);
    network_top_mux_3eOg_U38->din3(network_weights_weig_589);
    network_top_mux_3eOg_U38->din4(network_weights_weig_590);
    network_top_mux_3eOg_U38->din5(network_weights_weig_591);
    network_top_mux_3eOg_U38->din6(network_weights_weig_592);
    network_top_mux_3eOg_U38->din7(network_weights_weig_593);
    network_top_mux_3eOg_U38->din8(network_weights_weig_594);
    network_top_mux_3eOg_U38->din9(network_weights_weig_595);
    network_top_mux_3eOg_U38->din10(network_weights_weig_596);
    network_top_mux_3eOg_U38->din11(network_weights_weig_597);
    network_top_mux_3eOg_U38->din12(network_weights_weig_598);
    network_top_mux_3eOg_U38->din13(network_weights_weig_599);
    network_top_mux_3eOg_U38->din14(network_weights_weig_600);
    network_top_mux_3eOg_U38->din15(network_weights_weig_601);
    network_top_mux_3eOg_U38->din16(network_weights_weig_602);
    network_top_mux_3eOg_U38->din17(network_weights_weig_603);
    network_top_mux_3eOg_U38->din18(network_weights_weig_604);
    network_top_mux_3eOg_U38->din19(network_weights_weig_605);
    network_top_mux_3eOg_U38->din20(network_weights_weig_606);
    network_top_mux_3eOg_U38->din21(network_weights_weig_607);
    network_top_mux_3eOg_U38->din22(network_weights_weig_608);
    network_top_mux_3eOg_U38->din23(network_weights_weig_609);
    network_top_mux_3eOg_U38->din24(network_weights_weig_610);
    network_top_mux_3eOg_U38->din25(network_weights_weig_611);
    network_top_mux_3eOg_U38->din26(network_weights_weig_612);
    network_top_mux_3eOg_U38->din27(network_weights_weig_613);
    network_top_mux_3eOg_U38->din28(network_weights_weig_614);
    network_top_mux_3eOg_U38->din29(network_weights_weig_615);
    network_top_mux_3eOg_U38->din30(network_weights_weig_616);
    network_top_mux_3eOg_U38->din31(network_weights_weig_617);
    network_top_mux_3eOg_U38->din32(tmp_fu_1640_p33);
    network_top_mux_3eOg_U38->dout(tmp_fu_1640_p34);
    network_top_mux_1fYi_U39 = new network_top_mux_1fYi<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8>("network_top_mux_1fYi_U39");
    network_top_mux_1fYi_U39->din0(network_weights_weig_618);
    network_top_mux_1fYi_U39->din1(network_weights_weig_619);
    network_top_mux_1fYi_U39->din2(network_weights_weig_620);
    network_top_mux_1fYi_U39->din3(network_weights_weig_621);
    network_top_mux_1fYi_U39->din4(network_weights_weig_622);
    network_top_mux_1fYi_U39->din5(network_weights_weig_623);
    network_top_mux_1fYi_U39->din6(network_weights_weig_624);
    network_top_mux_1fYi_U39->din7(network_weights_weig_625);
    network_top_mux_1fYi_U39->din8(network_weights_weig_626);
    network_top_mux_1fYi_U39->din9(network_weights_weig_627);
    network_top_mux_1fYi_U39->din10(network_weights_weig_628);
    network_top_mux_1fYi_U39->din11(network_weights_weig_629);
    network_top_mux_1fYi_U39->din12(network_weights_weig_630);
    network_top_mux_1fYi_U39->din13(network_weights_weig_631);
    network_top_mux_1fYi_U39->din14(network_weights_weig_632);
    network_top_mux_1fYi_U39->din15(network_weights_weig_633);
    network_top_mux_1fYi_U39->din16(network_weights_weig_634);
    network_top_mux_1fYi_U39->din17(network_weights_weig_635);
    network_top_mux_1fYi_U39->din18(network_weights_weig_636);
    network_top_mux_1fYi_U39->din19(network_weights_weig_637);
    network_top_mux_1fYi_U39->din20(network_weights_weig_638);
    network_top_mux_1fYi_U39->din21(network_weights_weig_639);
    network_top_mux_1fYi_U39->din22(network_weights_weig_640);
    network_top_mux_1fYi_U39->din23(network_weights_weig_641);
    network_top_mux_1fYi_U39->din24(network_weights_weig_642);
    network_top_mux_1fYi_U39->din25(network_weights_weig_643);
    network_top_mux_1fYi_U39->din26(network_weights_weig_644);
    network_top_mux_1fYi_U39->din27(network_weights_weig_645);
    network_top_mux_1fYi_U39->din28(network_weights_weig_646);
    network_top_mux_1fYi_U39->din29(network_weights_weig_647);
    network_top_mux_1fYi_U39->din30(network_weights_weig_648);
    network_top_mux_1fYi_U39->din31(network_weights_weig_649);
    network_top_mux_1fYi_U39->din32(network_weights_weig_650);
    network_top_mux_1fYi_U39->din33(network_weights_weig_651);
    network_top_mux_1fYi_U39->din34(network_weights_weig_652);
    network_top_mux_1fYi_U39->din35(network_weights_weig_653);
    network_top_mux_1fYi_U39->din36(network_weights_weig_654);
    network_top_mux_1fYi_U39->din37(network_weights_weig_655);
    network_top_mux_1fYi_U39->din38(network_weights_weig_656);
    network_top_mux_1fYi_U39->din39(network_weights_weig_657);
    network_top_mux_1fYi_U39->din40(network_weights_weig_658);
    network_top_mux_1fYi_U39->din41(network_weights_weig_659);
    network_top_mux_1fYi_U39->din42(network_weights_weig_660);
    network_top_mux_1fYi_U39->din43(network_weights_weig_661);
    network_top_mux_1fYi_U39->din44(network_weights_weig_662);
    network_top_mux_1fYi_U39->din45(network_weights_weig_663);
    network_top_mux_1fYi_U39->din46(network_weights_weig_664);
    network_top_mux_1fYi_U39->din47(network_weights_weig_665);
    network_top_mux_1fYi_U39->din48(network_weights_weig_666);
    network_top_mux_1fYi_U39->din49(network_weights_weig_667);
    network_top_mux_1fYi_U39->din50(network_weights_weig_668);
    network_top_mux_1fYi_U39->din51(network_weights_weig_669);
    network_top_mux_1fYi_U39->din52(network_weights_weig_670);
    network_top_mux_1fYi_U39->din53(network_weights_weig_671);
    network_top_mux_1fYi_U39->din54(network_weights_weig_672);
    network_top_mux_1fYi_U39->din55(network_weights_weig_673);
    network_top_mux_1fYi_U39->din56(network_weights_weig_674);
    network_top_mux_1fYi_U39->din57(network_weights_weig_675);
    network_top_mux_1fYi_U39->din58(network_weights_weig_676);
    network_top_mux_1fYi_U39->din59(network_weights_weig_677);
    network_top_mux_1fYi_U39->din60(network_weights_weig_678);
    network_top_mux_1fYi_U39->din61(network_weights_weig_679);
    network_top_mux_1fYi_U39->din62(network_weights_weig_680);
    network_top_mux_1fYi_U39->din63(network_weights_weig_681);
    network_top_mux_1fYi_U39->din64(network_weights_weig_682);
    network_top_mux_1fYi_U39->din65(network_weights_weig_683);
    network_top_mux_1fYi_U39->din66(network_weights_weig_684);
    network_top_mux_1fYi_U39->din67(network_weights_weig_685);
    network_top_mux_1fYi_U39->din68(network_weights_weig_686);
    network_top_mux_1fYi_U39->din69(network_weights_weig_687);
    network_top_mux_1fYi_U39->din70(network_weights_weig_688);
    network_top_mux_1fYi_U39->din71(network_weights_weig_689);
    network_top_mux_1fYi_U39->din72(network_weights_weig_690);
    network_top_mux_1fYi_U39->din73(network_weights_weig_691);
    network_top_mux_1fYi_U39->din74(network_weights_weig_692);
    network_top_mux_1fYi_U39->din75(network_weights_weig_693);
    network_top_mux_1fYi_U39->din76(network_weights_weig_694);
    network_top_mux_1fYi_U39->din77(network_weights_weig_695);
    network_top_mux_1fYi_U39->din78(network_weights_weig_696);
    network_top_mux_1fYi_U39->din79(network_weights_weig_697);
    network_top_mux_1fYi_U39->din80(network_weights_weig_698);
    network_top_mux_1fYi_U39->din81(network_weights_weig_699);
    network_top_mux_1fYi_U39->din82(network_weights_weig_700);
    network_top_mux_1fYi_U39->din83(network_weights_weig_701);
    network_top_mux_1fYi_U39->din84(network_weights_weig_702);
    network_top_mux_1fYi_U39->din85(network_weights_weig_703);
    network_top_mux_1fYi_U39->din86(network_weights_weig_704);
    network_top_mux_1fYi_U39->din87(network_weights_weig_705);
    network_top_mux_1fYi_U39->din88(network_weights_weig_706);
    network_top_mux_1fYi_U39->din89(network_weights_weig_707);
    network_top_mux_1fYi_U39->din90(network_weights_weig_708);
    network_top_mux_1fYi_U39->din91(network_weights_weig_709);
    network_top_mux_1fYi_U39->din92(network_weights_weig_710);
    network_top_mux_1fYi_U39->din93(network_weights_weig_711);
    network_top_mux_1fYi_U39->din94(network_weights_weig_712);
    network_top_mux_1fYi_U39->din95(network_weights_weig_713);
    network_top_mux_1fYi_U39->din96(network_weights_weig_714);
    network_top_mux_1fYi_U39->din97(network_weights_weig_715);
    network_top_mux_1fYi_U39->din98(network_weights_weig_716);
    network_top_mux_1fYi_U39->din99(network_weights_weig_717);
    network_top_mux_1fYi_U39->din100(network_weights_weig_718);
    network_top_mux_1fYi_U39->din101(network_weights_weig_719);
    network_top_mux_1fYi_U39->din102(network_weights_weig_720);
    network_top_mux_1fYi_U39->din103(network_weights_weig_721);
    network_top_mux_1fYi_U39->din104(network_weights_weig_722);
    network_top_mux_1fYi_U39->din105(network_weights_weig_723);
    network_top_mux_1fYi_U39->din106(network_weights_weig_724);
    network_top_mux_1fYi_U39->din107(network_weights_weig_725);
    network_top_mux_1fYi_U39->din108(network_weights_weig_726);
    network_top_mux_1fYi_U39->din109(network_weights_weig_727);
    network_top_mux_1fYi_U39->din110(network_weights_weig_728);
    network_top_mux_1fYi_U39->din111(network_weights_weig_729);
    network_top_mux_1fYi_U39->din112(network_weights_weig_730);
    network_top_mux_1fYi_U39->din113(network_weights_weig_731);
    network_top_mux_1fYi_U39->din114(network_weights_weig_732);
    network_top_mux_1fYi_U39->din115(network_weights_weig_733);
    network_top_mux_1fYi_U39->din116(network_weights_weig_734);
    network_top_mux_1fYi_U39->din117(network_weights_weig_735);
    network_top_mux_1fYi_U39->din118(network_weights_weig_736);
    network_top_mux_1fYi_U39->din119(network_weights_weig_737);
    network_top_mux_1fYi_U39->din120(network_weights_weig_738);
    network_top_mux_1fYi_U39->din121(network_weights_weig_739);
    network_top_mux_1fYi_U39->din122(network_weights_weig_740);
    network_top_mux_1fYi_U39->din123(network_weights_weig_741);
    network_top_mux_1fYi_U39->din124(network_weights_weig_742);
    network_top_mux_1fYi_U39->din125(network_weights_weig_743);
    network_top_mux_1fYi_U39->din126(network_weights_weig_744);
    network_top_mux_1fYi_U39->din127(network_weights_weig_745);
    network_top_mux_1fYi_U39->din128(tmp_1_fu_1730_p129);
    network_top_mux_1fYi_U39->dout(tmp_1_fu_1730_p130);
    network_top_mux_3eOg_U40 = new network_top_mux_3eOg<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,6,8>("network_top_mux_3eOg_U40");
    network_top_mux_3eOg_U40->din0(network_weights_weig_746);
    network_top_mux_3eOg_U40->din1(network_weights_weig_747);
    network_top_mux_3eOg_U40->din2(network_weights_weig_748);
    network_top_mux_3eOg_U40->din3(network_weights_weig_749);
    network_top_mux_3eOg_U40->din4(network_weights_weig_750);
    network_top_mux_3eOg_U40->din5(network_weights_weig_751);
    network_top_mux_3eOg_U40->din6(network_weights_weig_752);
    network_top_mux_3eOg_U40->din7(network_weights_weig_753);
    network_top_mux_3eOg_U40->din8(network_weights_weig_754);
    network_top_mux_3eOg_U40->din9(network_weights_weig_755);
    network_top_mux_3eOg_U40->din10(network_weights_weig_756);
    network_top_mux_3eOg_U40->din11(network_weights_weig_757);
    network_top_mux_3eOg_U40->din12(network_weights_weig_758);
    network_top_mux_3eOg_U40->din13(network_weights_weig_759);
    network_top_mux_3eOg_U40->din14(network_weights_weig_760);
    network_top_mux_3eOg_U40->din15(network_weights_weig_761);
    network_top_mux_3eOg_U40->din16(network_weights_weig_762);
    network_top_mux_3eOg_U40->din17(network_weights_weig_763);
    network_top_mux_3eOg_U40->din18(network_weights_weig_764);
    network_top_mux_3eOg_U40->din19(network_weights_weig_765);
    network_top_mux_3eOg_U40->din20(network_weights_weig_766);
    network_top_mux_3eOg_U40->din21(network_weights_weig_767);
    network_top_mux_3eOg_U40->din22(network_weights_weig_768);
    network_top_mux_3eOg_U40->din23(network_weights_weig_769);
    network_top_mux_3eOg_U40->din24(network_weights_weig_770);
    network_top_mux_3eOg_U40->din25(network_weights_weig_771);
    network_top_mux_3eOg_U40->din26(network_weights_weig_772);
    network_top_mux_3eOg_U40->din27(network_weights_weig_773);
    network_top_mux_3eOg_U40->din28(network_weights_weig_774);
    network_top_mux_3eOg_U40->din29(network_weights_weig_775);
    network_top_mux_3eOg_U40->din30(network_weights_weig_776);
    network_top_mux_3eOg_U40->din31(network_weights_weig_777);
    network_top_mux_3eOg_U40->din32(tmp_2_fu_2012_p33);
    network_top_mux_3eOg_U40->dout(tmp_2_fu_2012_p34);
    network_top_mux_4g8j_U41 = new network_top_mux_4g8j<1,1,8,8,8,8,2,8>("network_top_mux_4g8j_U41");
    network_top_mux_4g8j_U41->din0(network_weights_weig_778);
    network_top_mux_4g8j_U41->din1(network_weights_weig_779);
    network_top_mux_4g8j_U41->din2(network_weights_weig_780);
    network_top_mux_4g8j_U41->din3(network_weights_weig_781);
    network_top_mux_4g8j_U41->din4(tmp_3_fu_2086_p5);
    network_top_mux_4g8j_U41->dout(tmp_3_fu_2086_p6);

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( or_ln9_2_fu_2164_p2 );
    sensitive << ( select_ln9_2_fu_2156_p3 );

    SC_METHOD(thread_icmp_ln9_1_fu_2110_p2);
    sensitive << ( trunc_ln9_fu_2100_p1 );

    SC_METHOD(thread_icmp_ln9_2_fu_2116_p2);
    sensitive << ( trunc_ln9_fu_2100_p1 );

    SC_METHOD(thread_icmp_ln9_3_fu_2122_p2);
    sensitive << ( trunc_ln9_fu_2100_p1 );

    SC_METHOD(thread_icmp_ln9_fu_2104_p2);
    sensitive << ( trunc_ln9_fu_2100_p1 );

    SC_METHOD(thread_or_ln9_1_fu_2150_p2);
    sensitive << ( icmp_ln9_1_fu_2110_p2 );
    sensitive << ( icmp_ln9_fu_2104_p2 );

    SC_METHOD(thread_or_ln9_2_fu_2164_p2);
    sensitive << ( or_ln9_fu_2136_p2 );
    sensitive << ( or_ln9_1_fu_2150_p2 );

    SC_METHOD(thread_or_ln9_fu_2136_p2);
    sensitive << ( icmp_ln9_3_fu_2122_p2 );
    sensitive << ( icmp_ln9_2_fu_2116_p2 );

    SC_METHOD(thread_select_ln9_1_fu_2142_p3);
    sensitive << ( icmp_ln9_1_fu_2110_p2 );
    sensitive << ( tmp_2_fu_2012_p34 );
    sensitive << ( tmp_3_fu_2086_p6 );

    SC_METHOD(thread_select_ln9_2_fu_2156_p3);
    sensitive << ( or_ln9_fu_2136_p2 );
    sensitive << ( select_ln9_fu_2128_p3 );
    sensitive << ( select_ln9_1_fu_2142_p3 );

    SC_METHOD(thread_select_ln9_fu_2128_p3);
    sensitive << ( icmp_ln9_3_fu_2122_p2 );
    sensitive << ( tmp_fu_1640_p34 );
    sensitive << ( tmp_1_fu_1730_p130 );

    SC_METHOD(thread_tmp_1_fu_1730_p129);
    sensitive << ( tmp_5_fu_1718_p3 );

    SC_METHOD(thread_tmp_2_fu_2012_p33);
    sensitive << ( tmp_6_fu_2000_p3 );

    SC_METHOD(thread_tmp_3_fu_2086_p5);
    sensitive << ( index_1 );

    SC_METHOD(thread_tmp_4_fu_1628_p3);
    sensitive << ( trunc_ln12_fu_1620_p1 );
    sensitive << ( trunc_ln12_1_fu_1624_p1 );

    SC_METHOD(thread_tmp_5_fu_1718_p3);
    sensitive << ( trunc_ln15_fu_1710_p1 );
    sensitive << ( trunc_ln15_1_fu_1714_p1 );

    SC_METHOD(thread_tmp_6_fu_2000_p3);
    sensitive << ( trunc_ln18_fu_1992_p1 );
    sensitive << ( trunc_ln18_1_fu_1996_p1 );

    SC_METHOD(thread_tmp_fu_1640_p33);
    sensitive << ( tmp_4_fu_1628_p3 );

    SC_METHOD(thread_trunc_ln12_1_fu_1624_p1);
    sensitive << ( index_1 );

    SC_METHOD(thread_trunc_ln12_fu_1620_p1);
    sensitive << ( index_0 );

    SC_METHOD(thread_trunc_ln15_1_fu_1714_p1);
    sensitive << ( index_1 );

    SC_METHOD(thread_trunc_ln15_fu_1710_p1);
    sensitive << ( index_0 );

    SC_METHOD(thread_trunc_ln18_1_fu_1996_p1);
    sensitive << ( index_1 );

    SC_METHOD(thread_trunc_ln18_fu_1992_p1);
    sensitive << ( index_0 );

    SC_METHOD(thread_trunc_ln9_fu_2100_p1);
    sensitive << ( layer );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "getWeight_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, network_weights_weig, "(port)network_weights_weig");
    sc_trace(mVcdFile, network_weights_weig_587, "(port)network_weights_weig_587");
    sc_trace(mVcdFile, network_weights_weig_588, "(port)network_weights_weig_588");
    sc_trace(mVcdFile, network_weights_weig_589, "(port)network_weights_weig_589");
    sc_trace(mVcdFile, network_weights_weig_590, "(port)network_weights_weig_590");
    sc_trace(mVcdFile, network_weights_weig_591, "(port)network_weights_weig_591");
    sc_trace(mVcdFile, network_weights_weig_592, "(port)network_weights_weig_592");
    sc_trace(mVcdFile, network_weights_weig_593, "(port)network_weights_weig_593");
    sc_trace(mVcdFile, network_weights_weig_594, "(port)network_weights_weig_594");
    sc_trace(mVcdFile, network_weights_weig_595, "(port)network_weights_weig_595");
    sc_trace(mVcdFile, network_weights_weig_596, "(port)network_weights_weig_596");
    sc_trace(mVcdFile, network_weights_weig_597, "(port)network_weights_weig_597");
    sc_trace(mVcdFile, network_weights_weig_598, "(port)network_weights_weig_598");
    sc_trace(mVcdFile, network_weights_weig_599, "(port)network_weights_weig_599");
    sc_trace(mVcdFile, network_weights_weig_600, "(port)network_weights_weig_600");
    sc_trace(mVcdFile, network_weights_weig_601, "(port)network_weights_weig_601");
    sc_trace(mVcdFile, network_weights_weig_602, "(port)network_weights_weig_602");
    sc_trace(mVcdFile, network_weights_weig_603, "(port)network_weights_weig_603");
    sc_trace(mVcdFile, network_weights_weig_604, "(port)network_weights_weig_604");
    sc_trace(mVcdFile, network_weights_weig_605, "(port)network_weights_weig_605");
    sc_trace(mVcdFile, network_weights_weig_606, "(port)network_weights_weig_606");
    sc_trace(mVcdFile, network_weights_weig_607, "(port)network_weights_weig_607");
    sc_trace(mVcdFile, network_weights_weig_608, "(port)network_weights_weig_608");
    sc_trace(mVcdFile, network_weights_weig_609, "(port)network_weights_weig_609");
    sc_trace(mVcdFile, network_weights_weig_610, "(port)network_weights_weig_610");
    sc_trace(mVcdFile, network_weights_weig_611, "(port)network_weights_weig_611");
    sc_trace(mVcdFile, network_weights_weig_612, "(port)network_weights_weig_612");
    sc_trace(mVcdFile, network_weights_weig_613, "(port)network_weights_weig_613");
    sc_trace(mVcdFile, network_weights_weig_614, "(port)network_weights_weig_614");
    sc_trace(mVcdFile, network_weights_weig_615, "(port)network_weights_weig_615");
    sc_trace(mVcdFile, network_weights_weig_616, "(port)network_weights_weig_616");
    sc_trace(mVcdFile, network_weights_weig_617, "(port)network_weights_weig_617");
    sc_trace(mVcdFile, network_weights_weig_618, "(port)network_weights_weig_618");
    sc_trace(mVcdFile, network_weights_weig_619, "(port)network_weights_weig_619");
    sc_trace(mVcdFile, network_weights_weig_620, "(port)network_weights_weig_620");
    sc_trace(mVcdFile, network_weights_weig_621, "(port)network_weights_weig_621");
    sc_trace(mVcdFile, network_weights_weig_622, "(port)network_weights_weig_622");
    sc_trace(mVcdFile, network_weights_weig_623, "(port)network_weights_weig_623");
    sc_trace(mVcdFile, network_weights_weig_624, "(port)network_weights_weig_624");
    sc_trace(mVcdFile, network_weights_weig_625, "(port)network_weights_weig_625");
    sc_trace(mVcdFile, network_weights_weig_626, "(port)network_weights_weig_626");
    sc_trace(mVcdFile, network_weights_weig_627, "(port)network_weights_weig_627");
    sc_trace(mVcdFile, network_weights_weig_628, "(port)network_weights_weig_628");
    sc_trace(mVcdFile, network_weights_weig_629, "(port)network_weights_weig_629");
    sc_trace(mVcdFile, network_weights_weig_630, "(port)network_weights_weig_630");
    sc_trace(mVcdFile, network_weights_weig_631, "(port)network_weights_weig_631");
    sc_trace(mVcdFile, network_weights_weig_632, "(port)network_weights_weig_632");
    sc_trace(mVcdFile, network_weights_weig_633, "(port)network_weights_weig_633");
    sc_trace(mVcdFile, network_weights_weig_634, "(port)network_weights_weig_634");
    sc_trace(mVcdFile, network_weights_weig_635, "(port)network_weights_weig_635");
    sc_trace(mVcdFile, network_weights_weig_636, "(port)network_weights_weig_636");
    sc_trace(mVcdFile, network_weights_weig_637, "(port)network_weights_weig_637");
    sc_trace(mVcdFile, network_weights_weig_638, "(port)network_weights_weig_638");
    sc_trace(mVcdFile, network_weights_weig_639, "(port)network_weights_weig_639");
    sc_trace(mVcdFile, network_weights_weig_640, "(port)network_weights_weig_640");
    sc_trace(mVcdFile, network_weights_weig_641, "(port)network_weights_weig_641");
    sc_trace(mVcdFile, network_weights_weig_642, "(port)network_weights_weig_642");
    sc_trace(mVcdFile, network_weights_weig_643, "(port)network_weights_weig_643");
    sc_trace(mVcdFile, network_weights_weig_644, "(port)network_weights_weig_644");
    sc_trace(mVcdFile, network_weights_weig_645, "(port)network_weights_weig_645");
    sc_trace(mVcdFile, network_weights_weig_646, "(port)network_weights_weig_646");
    sc_trace(mVcdFile, network_weights_weig_647, "(port)network_weights_weig_647");
    sc_trace(mVcdFile, network_weights_weig_648, "(port)network_weights_weig_648");
    sc_trace(mVcdFile, network_weights_weig_649, "(port)network_weights_weig_649");
    sc_trace(mVcdFile, network_weights_weig_650, "(port)network_weights_weig_650");
    sc_trace(mVcdFile, network_weights_weig_651, "(port)network_weights_weig_651");
    sc_trace(mVcdFile, network_weights_weig_652, "(port)network_weights_weig_652");
    sc_trace(mVcdFile, network_weights_weig_653, "(port)network_weights_weig_653");
    sc_trace(mVcdFile, network_weights_weig_654, "(port)network_weights_weig_654");
    sc_trace(mVcdFile, network_weights_weig_655, "(port)network_weights_weig_655");
    sc_trace(mVcdFile, network_weights_weig_656, "(port)network_weights_weig_656");
    sc_trace(mVcdFile, network_weights_weig_657, "(port)network_weights_weig_657");
    sc_trace(mVcdFile, network_weights_weig_658, "(port)network_weights_weig_658");
    sc_trace(mVcdFile, network_weights_weig_659, "(port)network_weights_weig_659");
    sc_trace(mVcdFile, network_weights_weig_660, "(port)network_weights_weig_660");
    sc_trace(mVcdFile, network_weights_weig_661, "(port)network_weights_weig_661");
    sc_trace(mVcdFile, network_weights_weig_662, "(port)network_weights_weig_662");
    sc_trace(mVcdFile, network_weights_weig_663, "(port)network_weights_weig_663");
    sc_trace(mVcdFile, network_weights_weig_664, "(port)network_weights_weig_664");
    sc_trace(mVcdFile, network_weights_weig_665, "(port)network_weights_weig_665");
    sc_trace(mVcdFile, network_weights_weig_666, "(port)network_weights_weig_666");
    sc_trace(mVcdFile, network_weights_weig_667, "(port)network_weights_weig_667");
    sc_trace(mVcdFile, network_weights_weig_668, "(port)network_weights_weig_668");
    sc_trace(mVcdFile, network_weights_weig_669, "(port)network_weights_weig_669");
    sc_trace(mVcdFile, network_weights_weig_670, "(port)network_weights_weig_670");
    sc_trace(mVcdFile, network_weights_weig_671, "(port)network_weights_weig_671");
    sc_trace(mVcdFile, network_weights_weig_672, "(port)network_weights_weig_672");
    sc_trace(mVcdFile, network_weights_weig_673, "(port)network_weights_weig_673");
    sc_trace(mVcdFile, network_weights_weig_674, "(port)network_weights_weig_674");
    sc_trace(mVcdFile, network_weights_weig_675, "(port)network_weights_weig_675");
    sc_trace(mVcdFile, network_weights_weig_676, "(port)network_weights_weig_676");
    sc_trace(mVcdFile, network_weights_weig_677, "(port)network_weights_weig_677");
    sc_trace(mVcdFile, network_weights_weig_678, "(port)network_weights_weig_678");
    sc_trace(mVcdFile, network_weights_weig_679, "(port)network_weights_weig_679");
    sc_trace(mVcdFile, network_weights_weig_680, "(port)network_weights_weig_680");
    sc_trace(mVcdFile, network_weights_weig_681, "(port)network_weights_weig_681");
    sc_trace(mVcdFile, network_weights_weig_682, "(port)network_weights_weig_682");
    sc_trace(mVcdFile, network_weights_weig_683, "(port)network_weights_weig_683");
    sc_trace(mVcdFile, network_weights_weig_684, "(port)network_weights_weig_684");
    sc_trace(mVcdFile, network_weights_weig_685, "(port)network_weights_weig_685");
    sc_trace(mVcdFile, network_weights_weig_686, "(port)network_weights_weig_686");
    sc_trace(mVcdFile, network_weights_weig_687, "(port)network_weights_weig_687");
    sc_trace(mVcdFile, network_weights_weig_688, "(port)network_weights_weig_688");
    sc_trace(mVcdFile, network_weights_weig_689, "(port)network_weights_weig_689");
    sc_trace(mVcdFile, network_weights_weig_690, "(port)network_weights_weig_690");
    sc_trace(mVcdFile, network_weights_weig_691, "(port)network_weights_weig_691");
    sc_trace(mVcdFile, network_weights_weig_692, "(port)network_weights_weig_692");
    sc_trace(mVcdFile, network_weights_weig_693, "(port)network_weights_weig_693");
    sc_trace(mVcdFile, network_weights_weig_694, "(port)network_weights_weig_694");
    sc_trace(mVcdFile, network_weights_weig_695, "(port)network_weights_weig_695");
    sc_trace(mVcdFile, network_weights_weig_696, "(port)network_weights_weig_696");
    sc_trace(mVcdFile, network_weights_weig_697, "(port)network_weights_weig_697");
    sc_trace(mVcdFile, network_weights_weig_698, "(port)network_weights_weig_698");
    sc_trace(mVcdFile, network_weights_weig_699, "(port)network_weights_weig_699");
    sc_trace(mVcdFile, network_weights_weig_700, "(port)network_weights_weig_700");
    sc_trace(mVcdFile, network_weights_weig_701, "(port)network_weights_weig_701");
    sc_trace(mVcdFile, network_weights_weig_702, "(port)network_weights_weig_702");
    sc_trace(mVcdFile, network_weights_weig_703, "(port)network_weights_weig_703");
    sc_trace(mVcdFile, network_weights_weig_704, "(port)network_weights_weig_704");
    sc_trace(mVcdFile, network_weights_weig_705, "(port)network_weights_weig_705");
    sc_trace(mVcdFile, network_weights_weig_706, "(port)network_weights_weig_706");
    sc_trace(mVcdFile, network_weights_weig_707, "(port)network_weights_weig_707");
    sc_trace(mVcdFile, network_weights_weig_708, "(port)network_weights_weig_708");
    sc_trace(mVcdFile, network_weights_weig_709, "(port)network_weights_weig_709");
    sc_trace(mVcdFile, network_weights_weig_710, "(port)network_weights_weig_710");
    sc_trace(mVcdFile, network_weights_weig_711, "(port)network_weights_weig_711");
    sc_trace(mVcdFile, network_weights_weig_712, "(port)network_weights_weig_712");
    sc_trace(mVcdFile, network_weights_weig_713, "(port)network_weights_weig_713");
    sc_trace(mVcdFile, network_weights_weig_714, "(port)network_weights_weig_714");
    sc_trace(mVcdFile, network_weights_weig_715, "(port)network_weights_weig_715");
    sc_trace(mVcdFile, network_weights_weig_716, "(port)network_weights_weig_716");
    sc_trace(mVcdFile, network_weights_weig_717, "(port)network_weights_weig_717");
    sc_trace(mVcdFile, network_weights_weig_718, "(port)network_weights_weig_718");
    sc_trace(mVcdFile, network_weights_weig_719, "(port)network_weights_weig_719");
    sc_trace(mVcdFile, network_weights_weig_720, "(port)network_weights_weig_720");
    sc_trace(mVcdFile, network_weights_weig_721, "(port)network_weights_weig_721");
    sc_trace(mVcdFile, network_weights_weig_722, "(port)network_weights_weig_722");
    sc_trace(mVcdFile, network_weights_weig_723, "(port)network_weights_weig_723");
    sc_trace(mVcdFile, network_weights_weig_724, "(port)network_weights_weig_724");
    sc_trace(mVcdFile, network_weights_weig_725, "(port)network_weights_weig_725");
    sc_trace(mVcdFile, network_weights_weig_726, "(port)network_weights_weig_726");
    sc_trace(mVcdFile, network_weights_weig_727, "(port)network_weights_weig_727");
    sc_trace(mVcdFile, network_weights_weig_728, "(port)network_weights_weig_728");
    sc_trace(mVcdFile, network_weights_weig_729, "(port)network_weights_weig_729");
    sc_trace(mVcdFile, network_weights_weig_730, "(port)network_weights_weig_730");
    sc_trace(mVcdFile, network_weights_weig_731, "(port)network_weights_weig_731");
    sc_trace(mVcdFile, network_weights_weig_732, "(port)network_weights_weig_732");
    sc_trace(mVcdFile, network_weights_weig_733, "(port)network_weights_weig_733");
    sc_trace(mVcdFile, network_weights_weig_734, "(port)network_weights_weig_734");
    sc_trace(mVcdFile, network_weights_weig_735, "(port)network_weights_weig_735");
    sc_trace(mVcdFile, network_weights_weig_736, "(port)network_weights_weig_736");
    sc_trace(mVcdFile, network_weights_weig_737, "(port)network_weights_weig_737");
    sc_trace(mVcdFile, network_weights_weig_738, "(port)network_weights_weig_738");
    sc_trace(mVcdFile, network_weights_weig_739, "(port)network_weights_weig_739");
    sc_trace(mVcdFile, network_weights_weig_740, "(port)network_weights_weig_740");
    sc_trace(mVcdFile, network_weights_weig_741, "(port)network_weights_weig_741");
    sc_trace(mVcdFile, network_weights_weig_742, "(port)network_weights_weig_742");
    sc_trace(mVcdFile, network_weights_weig_743, "(port)network_weights_weig_743");
    sc_trace(mVcdFile, network_weights_weig_744, "(port)network_weights_weig_744");
    sc_trace(mVcdFile, network_weights_weig_745, "(port)network_weights_weig_745");
    sc_trace(mVcdFile, network_weights_weig_746, "(port)network_weights_weig_746");
    sc_trace(mVcdFile, network_weights_weig_747, "(port)network_weights_weig_747");
    sc_trace(mVcdFile, network_weights_weig_748, "(port)network_weights_weig_748");
    sc_trace(mVcdFile, network_weights_weig_749, "(port)network_weights_weig_749");
    sc_trace(mVcdFile, network_weights_weig_750, "(port)network_weights_weig_750");
    sc_trace(mVcdFile, network_weights_weig_751, "(port)network_weights_weig_751");
    sc_trace(mVcdFile, network_weights_weig_752, "(port)network_weights_weig_752");
    sc_trace(mVcdFile, network_weights_weig_753, "(port)network_weights_weig_753");
    sc_trace(mVcdFile, network_weights_weig_754, "(port)network_weights_weig_754");
    sc_trace(mVcdFile, network_weights_weig_755, "(port)network_weights_weig_755");
    sc_trace(mVcdFile, network_weights_weig_756, "(port)network_weights_weig_756");
    sc_trace(mVcdFile, network_weights_weig_757, "(port)network_weights_weig_757");
    sc_trace(mVcdFile, network_weights_weig_758, "(port)network_weights_weig_758");
    sc_trace(mVcdFile, network_weights_weig_759, "(port)network_weights_weig_759");
    sc_trace(mVcdFile, network_weights_weig_760, "(port)network_weights_weig_760");
    sc_trace(mVcdFile, network_weights_weig_761, "(port)network_weights_weig_761");
    sc_trace(mVcdFile, network_weights_weig_762, "(port)network_weights_weig_762");
    sc_trace(mVcdFile, network_weights_weig_763, "(port)network_weights_weig_763");
    sc_trace(mVcdFile, network_weights_weig_764, "(port)network_weights_weig_764");
    sc_trace(mVcdFile, network_weights_weig_765, "(port)network_weights_weig_765");
    sc_trace(mVcdFile, network_weights_weig_766, "(port)network_weights_weig_766");
    sc_trace(mVcdFile, network_weights_weig_767, "(port)network_weights_weig_767");
    sc_trace(mVcdFile, network_weights_weig_768, "(port)network_weights_weig_768");
    sc_trace(mVcdFile, network_weights_weig_769, "(port)network_weights_weig_769");
    sc_trace(mVcdFile, network_weights_weig_770, "(port)network_weights_weig_770");
    sc_trace(mVcdFile, network_weights_weig_771, "(port)network_weights_weig_771");
    sc_trace(mVcdFile, network_weights_weig_772, "(port)network_weights_weig_772");
    sc_trace(mVcdFile, network_weights_weig_773, "(port)network_weights_weig_773");
    sc_trace(mVcdFile, network_weights_weig_774, "(port)network_weights_weig_774");
    sc_trace(mVcdFile, network_weights_weig_775, "(port)network_weights_weig_775");
    sc_trace(mVcdFile, network_weights_weig_776, "(port)network_weights_weig_776");
    sc_trace(mVcdFile, network_weights_weig_777, "(port)network_weights_weig_777");
    sc_trace(mVcdFile, network_weights_weig_778, "(port)network_weights_weig_778");
    sc_trace(mVcdFile, network_weights_weig_779, "(port)network_weights_weig_779");
    sc_trace(mVcdFile, network_weights_weig_780, "(port)network_weights_weig_780");
    sc_trace(mVcdFile, network_weights_weig_781, "(port)network_weights_weig_781");
    sc_trace(mVcdFile, layer, "(port)layer");
    sc_trace(mVcdFile, index_0, "(port)index_0");
    sc_trace(mVcdFile, index_1, "(port)index_1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, trunc_ln12_fu_1620_p1, "trunc_ln12_fu_1620_p1");
    sc_trace(mVcdFile, trunc_ln12_1_fu_1624_p1, "trunc_ln12_1_fu_1624_p1");
    sc_trace(mVcdFile, tmp_4_fu_1628_p3, "tmp_4_fu_1628_p3");
    sc_trace(mVcdFile, tmp_fu_1640_p33, "tmp_fu_1640_p33");
    sc_trace(mVcdFile, trunc_ln15_fu_1710_p1, "trunc_ln15_fu_1710_p1");
    sc_trace(mVcdFile, trunc_ln15_1_fu_1714_p1, "trunc_ln15_1_fu_1714_p1");
    sc_trace(mVcdFile, tmp_5_fu_1718_p3, "tmp_5_fu_1718_p3");
    sc_trace(mVcdFile, tmp_1_fu_1730_p129, "tmp_1_fu_1730_p129");
    sc_trace(mVcdFile, trunc_ln18_fu_1992_p1, "trunc_ln18_fu_1992_p1");
    sc_trace(mVcdFile, trunc_ln18_1_fu_1996_p1, "trunc_ln18_1_fu_1996_p1");
    sc_trace(mVcdFile, tmp_6_fu_2000_p3, "tmp_6_fu_2000_p3");
    sc_trace(mVcdFile, tmp_2_fu_2012_p33, "tmp_2_fu_2012_p33");
    sc_trace(mVcdFile, tmp_3_fu_2086_p5, "tmp_3_fu_2086_p5");
    sc_trace(mVcdFile, trunc_ln9_fu_2100_p1, "trunc_ln9_fu_2100_p1");
    sc_trace(mVcdFile, icmp_ln9_3_fu_2122_p2, "icmp_ln9_3_fu_2122_p2");
    sc_trace(mVcdFile, tmp_fu_1640_p34, "tmp_fu_1640_p34");
    sc_trace(mVcdFile, tmp_1_fu_1730_p130, "tmp_1_fu_1730_p130");
    sc_trace(mVcdFile, icmp_ln9_2_fu_2116_p2, "icmp_ln9_2_fu_2116_p2");
    sc_trace(mVcdFile, icmp_ln9_1_fu_2110_p2, "icmp_ln9_1_fu_2110_p2");
    sc_trace(mVcdFile, tmp_2_fu_2012_p34, "tmp_2_fu_2012_p34");
    sc_trace(mVcdFile, tmp_3_fu_2086_p6, "tmp_3_fu_2086_p6");
    sc_trace(mVcdFile, icmp_ln9_fu_2104_p2, "icmp_ln9_fu_2104_p2");
    sc_trace(mVcdFile, or_ln9_fu_2136_p2, "or_ln9_fu_2136_p2");
    sc_trace(mVcdFile, select_ln9_fu_2128_p3, "select_ln9_fu_2128_p3");
    sc_trace(mVcdFile, select_ln9_1_fu_2142_p3, "select_ln9_1_fu_2142_p3");
    sc_trace(mVcdFile, or_ln9_1_fu_2150_p2, "or_ln9_1_fu_2150_p2");
    sc_trace(mVcdFile, or_ln9_2_fu_2164_p2, "or_ln9_2_fu_2164_p2");
    sc_trace(mVcdFile, select_ln9_2_fu_2156_p3, "select_ln9_2_fu_2156_p3");
#endif

    }
}

getWeight::~getWeight() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete network_top_mux_3eOg_U38;
    delete network_top_mux_1fYi_U39;
    delete network_top_mux_3eOg_U40;
    delete network_top_mux_4g8j_U41;
}

void getWeight::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void getWeight::thread_ap_return() {
    ap_return = (!or_ln9_2_fu_2164_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln9_2_fu_2164_p2.read()[0].to_bool())? select_ln9_2_fu_2156_p3.read(): ap_const_lv8_0);
}

void getWeight::thread_icmp_ln9_1_fu_2110_p2() {
    icmp_ln9_1_fu_2110_p2 = (!trunc_ln9_fu_2100_p1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln9_fu_2100_p1.read() == ap_const_lv2_2);
}

void getWeight::thread_icmp_ln9_2_fu_2116_p2() {
    icmp_ln9_2_fu_2116_p2 = (!trunc_ln9_fu_2100_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln9_fu_2100_p1.read() == ap_const_lv2_1);
}

void getWeight::thread_icmp_ln9_3_fu_2122_p2() {
    icmp_ln9_3_fu_2122_p2 = (!trunc_ln9_fu_2100_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln9_fu_2100_p1.read() == ap_const_lv2_0);
}

void getWeight::thread_icmp_ln9_fu_2104_p2() {
    icmp_ln9_fu_2104_p2 = (!trunc_ln9_fu_2100_p1.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln9_fu_2100_p1.read() == ap_const_lv2_3);
}

void getWeight::thread_or_ln9_1_fu_2150_p2() {
    or_ln9_1_fu_2150_p2 = (icmp_ln9_1_fu_2110_p2.read() | icmp_ln9_fu_2104_p2.read());
}

void getWeight::thread_or_ln9_2_fu_2164_p2() {
    or_ln9_2_fu_2164_p2 = (or_ln9_fu_2136_p2.read() | or_ln9_1_fu_2150_p2.read());
}

void getWeight::thread_or_ln9_fu_2136_p2() {
    or_ln9_fu_2136_p2 = (icmp_ln9_3_fu_2122_p2.read() | icmp_ln9_2_fu_2116_p2.read());
}

void getWeight::thread_select_ln9_1_fu_2142_p3() {
    select_ln9_1_fu_2142_p3 = (!icmp_ln9_1_fu_2110_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln9_1_fu_2110_p2.read()[0].to_bool())? tmp_2_fu_2012_p34.read(): tmp_3_fu_2086_p6.read());
}

void getWeight::thread_select_ln9_2_fu_2156_p3() {
    select_ln9_2_fu_2156_p3 = (!or_ln9_fu_2136_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln9_fu_2136_p2.read()[0].to_bool())? select_ln9_fu_2128_p3.read(): select_ln9_1_fu_2142_p3.read());
}

void getWeight::thread_select_ln9_fu_2128_p3() {
    select_ln9_fu_2128_p3 = (!icmp_ln9_3_fu_2122_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln9_3_fu_2122_p2.read()[0].to_bool())? tmp_fu_1640_p34.read(): tmp_1_fu_1730_p130.read());
}

void getWeight::thread_tmp_1_fu_1730_p129() {
    tmp_1_fu_1730_p129 = esl_zext<8,7>(tmp_5_fu_1718_p3.read());
}

void getWeight::thread_tmp_2_fu_2012_p33() {
    tmp_2_fu_2012_p33 = esl_zext<6,5>(tmp_6_fu_2000_p3.read());
}

void getWeight::thread_tmp_3_fu_2086_p5() {
    tmp_3_fu_2086_p5 = index_1.read().range(2-1, 0);
}

void getWeight::thread_tmp_4_fu_1628_p3() {
    tmp_4_fu_1628_p3 = esl_concat<4,1>(trunc_ln12_fu_1620_p1.read(), trunc_ln12_1_fu_1624_p1.read());
}

void getWeight::thread_tmp_5_fu_1718_p3() {
    tmp_5_fu_1718_p3 = esl_concat<3,4>(trunc_ln15_fu_1710_p1.read(), trunc_ln15_1_fu_1714_p1.read());
}

void getWeight::thread_tmp_6_fu_2000_p3() {
    tmp_6_fu_2000_p3 = esl_concat<2,3>(trunc_ln18_fu_1992_p1.read(), trunc_ln18_1_fu_1996_p1.read());
}

void getWeight::thread_tmp_fu_1640_p33() {
    tmp_fu_1640_p33 = esl_zext<6,5>(tmp_4_fu_1628_p3.read());
}

void getWeight::thread_trunc_ln12_1_fu_1624_p1() {
    trunc_ln12_1_fu_1624_p1 = index_1.read().range(1-1, 0);
}

void getWeight::thread_trunc_ln12_fu_1620_p1() {
    trunc_ln12_fu_1620_p1 = index_0.read().range(4-1, 0);
}

void getWeight::thread_trunc_ln15_1_fu_1714_p1() {
    trunc_ln15_1_fu_1714_p1 = index_1.read().range(4-1, 0);
}

void getWeight::thread_trunc_ln15_fu_1710_p1() {
    trunc_ln15_fu_1710_p1 = index_0.read().range(3-1, 0);
}

void getWeight::thread_trunc_ln18_1_fu_1996_p1() {
    trunc_ln18_1_fu_1996_p1 = index_1.read().range(3-1, 0);
}

void getWeight::thread_trunc_ln18_fu_1992_p1() {
    trunc_ln18_fu_1992_p1 = index_0.read().range(2-1, 0);
}

void getWeight::thread_trunc_ln9_fu_2100_p1() {
    trunc_ln9_fu_2100_p1 = layer.read().range(2-1, 0);
}

}

