-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getWeight is
port (
    ap_ready : OUT STD_LOGIC;
    network_weights_weig : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_587 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_588 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_589 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_590 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_591 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_592 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_593 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_594 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_595 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_596 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_597 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_598 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_599 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_600 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_601 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_602 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_603 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_604 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_605 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_606 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_607 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_608 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_609 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_610 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_611 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_612 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_613 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_614 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_615 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_616 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_617 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_618 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_619 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_620 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_621 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_622 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_623 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_624 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_625 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_626 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_627 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_628 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_629 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_630 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_631 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_632 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_633 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_634 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_635 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_636 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_637 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_638 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_639 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_640 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_641 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_642 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_643 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_644 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_645 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_646 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_647 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_648 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_649 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_650 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_651 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_652 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_653 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_654 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_655 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_656 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_657 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_658 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_659 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_660 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_661 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_662 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_663 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_664 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_665 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_666 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_667 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_668 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_669 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_670 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_671 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_672 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_673 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_674 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_675 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_676 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_677 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_678 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_679 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_680 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_681 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_682 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_683 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_684 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_685 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_686 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_687 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_688 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_689 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_690 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_691 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_692 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_693 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_694 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_695 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_696 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_697 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_698 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_699 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_700 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_701 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_702 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_703 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_704 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_705 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_706 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_707 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_708 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_709 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_710 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_711 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_712 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_713 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_714 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_715 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_716 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_717 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_718 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_719 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_720 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_721 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_722 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_723 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_724 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_725 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_726 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_727 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_728 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_729 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_730 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_731 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_732 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_733 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_734 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_735 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_736 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_737 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_738 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_739 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_740 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_741 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_742 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_743 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_744 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_745 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_746 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_747 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_748 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_749 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_750 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_751 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_752 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_753 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_754 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_755 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_756 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_757 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_758 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_759 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_760 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_761 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_762 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_763 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_764 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_765 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_766 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_767 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_768 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_769 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_770 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_771 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_772 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_773 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_774 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_775 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_776 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_777 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_778 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_779 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_780 : IN STD_LOGIC_VECTOR (7 downto 0);
    network_weights_weig_781 : IN STD_LOGIC_VECTOR (7 downto 0);
    layer : IN STD_LOGIC_VECTOR (3 downto 0);
    index_0 : IN STD_LOGIC_VECTOR (4 downto 0);
    index_1 : IN STD_LOGIC_VECTOR (4 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of getWeight is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal trunc_ln12_fu_1620_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln12_1_fu_1624_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_1628_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_1640_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln15_fu_1710_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln15_1_fu_1714_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_fu_1718_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_1_fu_1730_p129 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln18_fu_1992_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln18_1_fu_1996_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_6_fu_2000_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_2012_p33 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_3_fu_2086_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln9_fu_2100_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln9_3_fu_2122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_1640_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_1730_p130 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln9_2_fu_2116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln9_1_fu_2110_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_2012_p34 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_2086_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln9_fu_2104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_fu_2136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_fu_2128_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln9_1_fu_2142_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln9_1_fu_2150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln9_2_fu_2164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln9_2_fu_2156_p3 : STD_LOGIC_VECTOR (7 downto 0);

    component network_top_mux_3eOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (7 downto 0);
        din17 : IN STD_LOGIC_VECTOR (7 downto 0);
        din18 : IN STD_LOGIC_VECTOR (7 downto 0);
        din19 : IN STD_LOGIC_VECTOR (7 downto 0);
        din20 : IN STD_LOGIC_VECTOR (7 downto 0);
        din21 : IN STD_LOGIC_VECTOR (7 downto 0);
        din22 : IN STD_LOGIC_VECTOR (7 downto 0);
        din23 : IN STD_LOGIC_VECTOR (7 downto 0);
        din24 : IN STD_LOGIC_VECTOR (7 downto 0);
        din25 : IN STD_LOGIC_VECTOR (7 downto 0);
        din26 : IN STD_LOGIC_VECTOR (7 downto 0);
        din27 : IN STD_LOGIC_VECTOR (7 downto 0);
        din28 : IN STD_LOGIC_VECTOR (7 downto 0);
        din29 : IN STD_LOGIC_VECTOR (7 downto 0);
        din30 : IN STD_LOGIC_VECTOR (7 downto 0);
        din31 : IN STD_LOGIC_VECTOR (7 downto 0);
        din32 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component network_top_mux_1fYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        din17_WIDTH : INTEGER;
        din18_WIDTH : INTEGER;
        din19_WIDTH : INTEGER;
        din20_WIDTH : INTEGER;
        din21_WIDTH : INTEGER;
        din22_WIDTH : INTEGER;
        din23_WIDTH : INTEGER;
        din24_WIDTH : INTEGER;
        din25_WIDTH : INTEGER;
        din26_WIDTH : INTEGER;
        din27_WIDTH : INTEGER;
        din28_WIDTH : INTEGER;
        din29_WIDTH : INTEGER;
        din30_WIDTH : INTEGER;
        din31_WIDTH : INTEGER;
        din32_WIDTH : INTEGER;
        din33_WIDTH : INTEGER;
        din34_WIDTH : INTEGER;
        din35_WIDTH : INTEGER;
        din36_WIDTH : INTEGER;
        din37_WIDTH : INTEGER;
        din38_WIDTH : INTEGER;
        din39_WIDTH : INTEGER;
        din40_WIDTH : INTEGER;
        din41_WIDTH : INTEGER;
        din42_WIDTH : INTEGER;
        din43_WIDTH : INTEGER;
        din44_WIDTH : INTEGER;
        din45_WIDTH : INTEGER;
        din46_WIDTH : INTEGER;
        din47_WIDTH : INTEGER;
        din48_WIDTH : INTEGER;
        din49_WIDTH : INTEGER;
        din50_WIDTH : INTEGER;
        din51_WIDTH : INTEGER;
        din52_WIDTH : INTEGER;
        din53_WIDTH : INTEGER;
        din54_WIDTH : INTEGER;
        din55_WIDTH : INTEGER;
        din56_WIDTH : INTEGER;
        din57_WIDTH : INTEGER;
        din58_WIDTH : INTEGER;
        din59_WIDTH : INTEGER;
        din60_WIDTH : INTEGER;
        din61_WIDTH : INTEGER;
        din62_WIDTH : INTEGER;
        din63_WIDTH : INTEGER;
        din64_WIDTH : INTEGER;
        din65_WIDTH : INTEGER;
        din66_WIDTH : INTEGER;
        din67_WIDTH : INTEGER;
        din68_WIDTH : INTEGER;
        din69_WIDTH : INTEGER;
        din70_WIDTH : INTEGER;
        din71_WIDTH : INTEGER;
        din72_WIDTH : INTEGER;
        din73_WIDTH : INTEGER;
        din74_WIDTH : INTEGER;
        din75_WIDTH : INTEGER;
        din76_WIDTH : INTEGER;
        din77_WIDTH : INTEGER;
        din78_WIDTH : INTEGER;
        din79_WIDTH : INTEGER;
        din80_WIDTH : INTEGER;
        din81_WIDTH : INTEGER;
        din82_WIDTH : INTEGER;
        din83_WIDTH : INTEGER;
        din84_WIDTH : INTEGER;
        din85_WIDTH : INTEGER;
        din86_WIDTH : INTEGER;
        din87_WIDTH : INTEGER;
        din88_WIDTH : INTEGER;
        din89_WIDTH : INTEGER;
        din90_WIDTH : INTEGER;
        din91_WIDTH : INTEGER;
        din92_WIDTH : INTEGER;
        din93_WIDTH : INTEGER;
        din94_WIDTH : INTEGER;
        din95_WIDTH : INTEGER;
        din96_WIDTH : INTEGER;
        din97_WIDTH : INTEGER;
        din98_WIDTH : INTEGER;
        din99_WIDTH : INTEGER;
        din100_WIDTH : INTEGER;
        din101_WIDTH : INTEGER;
        din102_WIDTH : INTEGER;
        din103_WIDTH : INTEGER;
        din104_WIDTH : INTEGER;
        din105_WIDTH : INTEGER;
        din106_WIDTH : INTEGER;
        din107_WIDTH : INTEGER;
        din108_WIDTH : INTEGER;
        din109_WIDTH : INTEGER;
        din110_WIDTH : INTEGER;
        din111_WIDTH : INTEGER;
        din112_WIDTH : INTEGER;
        din113_WIDTH : INTEGER;
        din114_WIDTH : INTEGER;
        din115_WIDTH : INTEGER;
        din116_WIDTH : INTEGER;
        din117_WIDTH : INTEGER;
        din118_WIDTH : INTEGER;
        din119_WIDTH : INTEGER;
        din120_WIDTH : INTEGER;
        din121_WIDTH : INTEGER;
        din122_WIDTH : INTEGER;
        din123_WIDTH : INTEGER;
        din124_WIDTH : INTEGER;
        din125_WIDTH : INTEGER;
        din126_WIDTH : INTEGER;
        din127_WIDTH : INTEGER;
        din128_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (7 downto 0);
        din5 : IN STD_LOGIC_VECTOR (7 downto 0);
        din6 : IN STD_LOGIC_VECTOR (7 downto 0);
        din7 : IN STD_LOGIC_VECTOR (7 downto 0);
        din8 : IN STD_LOGIC_VECTOR (7 downto 0);
        din9 : IN STD_LOGIC_VECTOR (7 downto 0);
        din10 : IN STD_LOGIC_VECTOR (7 downto 0);
        din11 : IN STD_LOGIC_VECTOR (7 downto 0);
        din12 : IN STD_LOGIC_VECTOR (7 downto 0);
        din13 : IN STD_LOGIC_VECTOR (7 downto 0);
        din14 : IN STD_LOGIC_VECTOR (7 downto 0);
        din15 : IN STD_LOGIC_VECTOR (7 downto 0);
        din16 : IN STD_LOGIC_VECTOR (7 downto 0);
        din17 : IN STD_LOGIC_VECTOR (7 downto 0);
        din18 : IN STD_LOGIC_VECTOR (7 downto 0);
        din19 : IN STD_LOGIC_VECTOR (7 downto 0);
        din20 : IN STD_LOGIC_VECTOR (7 downto 0);
        din21 : IN STD_LOGIC_VECTOR (7 downto 0);
        din22 : IN STD_LOGIC_VECTOR (7 downto 0);
        din23 : IN STD_LOGIC_VECTOR (7 downto 0);
        din24 : IN STD_LOGIC_VECTOR (7 downto 0);
        din25 : IN STD_LOGIC_VECTOR (7 downto 0);
        din26 : IN STD_LOGIC_VECTOR (7 downto 0);
        din27 : IN STD_LOGIC_VECTOR (7 downto 0);
        din28 : IN STD_LOGIC_VECTOR (7 downto 0);
        din29 : IN STD_LOGIC_VECTOR (7 downto 0);
        din30 : IN STD_LOGIC_VECTOR (7 downto 0);
        din31 : IN STD_LOGIC_VECTOR (7 downto 0);
        din32 : IN STD_LOGIC_VECTOR (7 downto 0);
        din33 : IN STD_LOGIC_VECTOR (7 downto 0);
        din34 : IN STD_LOGIC_VECTOR (7 downto 0);
        din35 : IN STD_LOGIC_VECTOR (7 downto 0);
        din36 : IN STD_LOGIC_VECTOR (7 downto 0);
        din37 : IN STD_LOGIC_VECTOR (7 downto 0);
        din38 : IN STD_LOGIC_VECTOR (7 downto 0);
        din39 : IN STD_LOGIC_VECTOR (7 downto 0);
        din40 : IN STD_LOGIC_VECTOR (7 downto 0);
        din41 : IN STD_LOGIC_VECTOR (7 downto 0);
        din42 : IN STD_LOGIC_VECTOR (7 downto 0);
        din43 : IN STD_LOGIC_VECTOR (7 downto 0);
        din44 : IN STD_LOGIC_VECTOR (7 downto 0);
        din45 : IN STD_LOGIC_VECTOR (7 downto 0);
        din46 : IN STD_LOGIC_VECTOR (7 downto 0);
        din47 : IN STD_LOGIC_VECTOR (7 downto 0);
        din48 : IN STD_LOGIC_VECTOR (7 downto 0);
        din49 : IN STD_LOGIC_VECTOR (7 downto 0);
        din50 : IN STD_LOGIC_VECTOR (7 downto 0);
        din51 : IN STD_LOGIC_VECTOR (7 downto 0);
        din52 : IN STD_LOGIC_VECTOR (7 downto 0);
        din53 : IN STD_LOGIC_VECTOR (7 downto 0);
        din54 : IN STD_LOGIC_VECTOR (7 downto 0);
        din55 : IN STD_LOGIC_VECTOR (7 downto 0);
        din56 : IN STD_LOGIC_VECTOR (7 downto 0);
        din57 : IN STD_LOGIC_VECTOR (7 downto 0);
        din58 : IN STD_LOGIC_VECTOR (7 downto 0);
        din59 : IN STD_LOGIC_VECTOR (7 downto 0);
        din60 : IN STD_LOGIC_VECTOR (7 downto 0);
        din61 : IN STD_LOGIC_VECTOR (7 downto 0);
        din62 : IN STD_LOGIC_VECTOR (7 downto 0);
        din63 : IN STD_LOGIC_VECTOR (7 downto 0);
        din64 : IN STD_LOGIC_VECTOR (7 downto 0);
        din65 : IN STD_LOGIC_VECTOR (7 downto 0);
        din66 : IN STD_LOGIC_VECTOR (7 downto 0);
        din67 : IN STD_LOGIC_VECTOR (7 downto 0);
        din68 : IN STD_LOGIC_VECTOR (7 downto 0);
        din69 : IN STD_LOGIC_VECTOR (7 downto 0);
        din70 : IN STD_LOGIC_VECTOR (7 downto 0);
        din71 : IN STD_LOGIC_VECTOR (7 downto 0);
        din72 : IN STD_LOGIC_VECTOR (7 downto 0);
        din73 : IN STD_LOGIC_VECTOR (7 downto 0);
        din74 : IN STD_LOGIC_VECTOR (7 downto 0);
        din75 : IN STD_LOGIC_VECTOR (7 downto 0);
        din76 : IN STD_LOGIC_VECTOR (7 downto 0);
        din77 : IN STD_LOGIC_VECTOR (7 downto 0);
        din78 : IN STD_LOGIC_VECTOR (7 downto 0);
        din79 : IN STD_LOGIC_VECTOR (7 downto 0);
        din80 : IN STD_LOGIC_VECTOR (7 downto 0);
        din81 : IN STD_LOGIC_VECTOR (7 downto 0);
        din82 : IN STD_LOGIC_VECTOR (7 downto 0);
        din83 : IN STD_LOGIC_VECTOR (7 downto 0);
        din84 : IN STD_LOGIC_VECTOR (7 downto 0);
        din85 : IN STD_LOGIC_VECTOR (7 downto 0);
        din86 : IN STD_LOGIC_VECTOR (7 downto 0);
        din87 : IN STD_LOGIC_VECTOR (7 downto 0);
        din88 : IN STD_LOGIC_VECTOR (7 downto 0);
        din89 : IN STD_LOGIC_VECTOR (7 downto 0);
        din90 : IN STD_LOGIC_VECTOR (7 downto 0);
        din91 : IN STD_LOGIC_VECTOR (7 downto 0);
        din92 : IN STD_LOGIC_VECTOR (7 downto 0);
        din93 : IN STD_LOGIC_VECTOR (7 downto 0);
        din94 : IN STD_LOGIC_VECTOR (7 downto 0);
        din95 : IN STD_LOGIC_VECTOR (7 downto 0);
        din96 : IN STD_LOGIC_VECTOR (7 downto 0);
        din97 : IN STD_LOGIC_VECTOR (7 downto 0);
        din98 : IN STD_LOGIC_VECTOR (7 downto 0);
        din99 : IN STD_LOGIC_VECTOR (7 downto 0);
        din100 : IN STD_LOGIC_VECTOR (7 downto 0);
        din101 : IN STD_LOGIC_VECTOR (7 downto 0);
        din102 : IN STD_LOGIC_VECTOR (7 downto 0);
        din103 : IN STD_LOGIC_VECTOR (7 downto 0);
        din104 : IN STD_LOGIC_VECTOR (7 downto 0);
        din105 : IN STD_LOGIC_VECTOR (7 downto 0);
        din106 : IN STD_LOGIC_VECTOR (7 downto 0);
        din107 : IN STD_LOGIC_VECTOR (7 downto 0);
        din108 : IN STD_LOGIC_VECTOR (7 downto 0);
        din109 : IN STD_LOGIC_VECTOR (7 downto 0);
        din110 : IN STD_LOGIC_VECTOR (7 downto 0);
        din111 : IN STD_LOGIC_VECTOR (7 downto 0);
        din112 : IN STD_LOGIC_VECTOR (7 downto 0);
        din113 : IN STD_LOGIC_VECTOR (7 downto 0);
        din114 : IN STD_LOGIC_VECTOR (7 downto 0);
        din115 : IN STD_LOGIC_VECTOR (7 downto 0);
        din116 : IN STD_LOGIC_VECTOR (7 downto 0);
        din117 : IN STD_LOGIC_VECTOR (7 downto 0);
        din118 : IN STD_LOGIC_VECTOR (7 downto 0);
        din119 : IN STD_LOGIC_VECTOR (7 downto 0);
        din120 : IN STD_LOGIC_VECTOR (7 downto 0);
        din121 : IN STD_LOGIC_VECTOR (7 downto 0);
        din122 : IN STD_LOGIC_VECTOR (7 downto 0);
        din123 : IN STD_LOGIC_VECTOR (7 downto 0);
        din124 : IN STD_LOGIC_VECTOR (7 downto 0);
        din125 : IN STD_LOGIC_VECTOR (7 downto 0);
        din126 : IN STD_LOGIC_VECTOR (7 downto 0);
        din127 : IN STD_LOGIC_VECTOR (7 downto 0);
        din128 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component network_top_mux_4g8j IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        din4 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    network_top_mux_3eOg_U38 : component network_top_mux_3eOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 6,
        dout_WIDTH => 8)
    port map (
        din0 => network_weights_weig,
        din1 => network_weights_weig_587,
        din2 => network_weights_weig_588,
        din3 => network_weights_weig_589,
        din4 => network_weights_weig_590,
        din5 => network_weights_weig_591,
        din6 => network_weights_weig_592,
        din7 => network_weights_weig_593,
        din8 => network_weights_weig_594,
        din9 => network_weights_weig_595,
        din10 => network_weights_weig_596,
        din11 => network_weights_weig_597,
        din12 => network_weights_weig_598,
        din13 => network_weights_weig_599,
        din14 => network_weights_weig_600,
        din15 => network_weights_weig_601,
        din16 => network_weights_weig_602,
        din17 => network_weights_weig_603,
        din18 => network_weights_weig_604,
        din19 => network_weights_weig_605,
        din20 => network_weights_weig_606,
        din21 => network_weights_weig_607,
        din22 => network_weights_weig_608,
        din23 => network_weights_weig_609,
        din24 => network_weights_weig_610,
        din25 => network_weights_weig_611,
        din26 => network_weights_weig_612,
        din27 => network_weights_weig_613,
        din28 => network_weights_weig_614,
        din29 => network_weights_weig_615,
        din30 => network_weights_weig_616,
        din31 => network_weights_weig_617,
        din32 => tmp_fu_1640_p33,
        dout => tmp_fu_1640_p34);

    network_top_mux_1fYi_U39 : component network_top_mux_1fYi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 8,
        din33_WIDTH => 8,
        din34_WIDTH => 8,
        din35_WIDTH => 8,
        din36_WIDTH => 8,
        din37_WIDTH => 8,
        din38_WIDTH => 8,
        din39_WIDTH => 8,
        din40_WIDTH => 8,
        din41_WIDTH => 8,
        din42_WIDTH => 8,
        din43_WIDTH => 8,
        din44_WIDTH => 8,
        din45_WIDTH => 8,
        din46_WIDTH => 8,
        din47_WIDTH => 8,
        din48_WIDTH => 8,
        din49_WIDTH => 8,
        din50_WIDTH => 8,
        din51_WIDTH => 8,
        din52_WIDTH => 8,
        din53_WIDTH => 8,
        din54_WIDTH => 8,
        din55_WIDTH => 8,
        din56_WIDTH => 8,
        din57_WIDTH => 8,
        din58_WIDTH => 8,
        din59_WIDTH => 8,
        din60_WIDTH => 8,
        din61_WIDTH => 8,
        din62_WIDTH => 8,
        din63_WIDTH => 8,
        din64_WIDTH => 8,
        din65_WIDTH => 8,
        din66_WIDTH => 8,
        din67_WIDTH => 8,
        din68_WIDTH => 8,
        din69_WIDTH => 8,
        din70_WIDTH => 8,
        din71_WIDTH => 8,
        din72_WIDTH => 8,
        din73_WIDTH => 8,
        din74_WIDTH => 8,
        din75_WIDTH => 8,
        din76_WIDTH => 8,
        din77_WIDTH => 8,
        din78_WIDTH => 8,
        din79_WIDTH => 8,
        din80_WIDTH => 8,
        din81_WIDTH => 8,
        din82_WIDTH => 8,
        din83_WIDTH => 8,
        din84_WIDTH => 8,
        din85_WIDTH => 8,
        din86_WIDTH => 8,
        din87_WIDTH => 8,
        din88_WIDTH => 8,
        din89_WIDTH => 8,
        din90_WIDTH => 8,
        din91_WIDTH => 8,
        din92_WIDTH => 8,
        din93_WIDTH => 8,
        din94_WIDTH => 8,
        din95_WIDTH => 8,
        din96_WIDTH => 8,
        din97_WIDTH => 8,
        din98_WIDTH => 8,
        din99_WIDTH => 8,
        din100_WIDTH => 8,
        din101_WIDTH => 8,
        din102_WIDTH => 8,
        din103_WIDTH => 8,
        din104_WIDTH => 8,
        din105_WIDTH => 8,
        din106_WIDTH => 8,
        din107_WIDTH => 8,
        din108_WIDTH => 8,
        din109_WIDTH => 8,
        din110_WIDTH => 8,
        din111_WIDTH => 8,
        din112_WIDTH => 8,
        din113_WIDTH => 8,
        din114_WIDTH => 8,
        din115_WIDTH => 8,
        din116_WIDTH => 8,
        din117_WIDTH => 8,
        din118_WIDTH => 8,
        din119_WIDTH => 8,
        din120_WIDTH => 8,
        din121_WIDTH => 8,
        din122_WIDTH => 8,
        din123_WIDTH => 8,
        din124_WIDTH => 8,
        din125_WIDTH => 8,
        din126_WIDTH => 8,
        din127_WIDTH => 8,
        din128_WIDTH => 8,
        dout_WIDTH => 8)
    port map (
        din0 => network_weights_weig_618,
        din1 => network_weights_weig_619,
        din2 => network_weights_weig_620,
        din3 => network_weights_weig_621,
        din4 => network_weights_weig_622,
        din5 => network_weights_weig_623,
        din6 => network_weights_weig_624,
        din7 => network_weights_weig_625,
        din8 => network_weights_weig_626,
        din9 => network_weights_weig_627,
        din10 => network_weights_weig_628,
        din11 => network_weights_weig_629,
        din12 => network_weights_weig_630,
        din13 => network_weights_weig_631,
        din14 => network_weights_weig_632,
        din15 => network_weights_weig_633,
        din16 => network_weights_weig_634,
        din17 => network_weights_weig_635,
        din18 => network_weights_weig_636,
        din19 => network_weights_weig_637,
        din20 => network_weights_weig_638,
        din21 => network_weights_weig_639,
        din22 => network_weights_weig_640,
        din23 => network_weights_weig_641,
        din24 => network_weights_weig_642,
        din25 => network_weights_weig_643,
        din26 => network_weights_weig_644,
        din27 => network_weights_weig_645,
        din28 => network_weights_weig_646,
        din29 => network_weights_weig_647,
        din30 => network_weights_weig_648,
        din31 => network_weights_weig_649,
        din32 => network_weights_weig_650,
        din33 => network_weights_weig_651,
        din34 => network_weights_weig_652,
        din35 => network_weights_weig_653,
        din36 => network_weights_weig_654,
        din37 => network_weights_weig_655,
        din38 => network_weights_weig_656,
        din39 => network_weights_weig_657,
        din40 => network_weights_weig_658,
        din41 => network_weights_weig_659,
        din42 => network_weights_weig_660,
        din43 => network_weights_weig_661,
        din44 => network_weights_weig_662,
        din45 => network_weights_weig_663,
        din46 => network_weights_weig_664,
        din47 => network_weights_weig_665,
        din48 => network_weights_weig_666,
        din49 => network_weights_weig_667,
        din50 => network_weights_weig_668,
        din51 => network_weights_weig_669,
        din52 => network_weights_weig_670,
        din53 => network_weights_weig_671,
        din54 => network_weights_weig_672,
        din55 => network_weights_weig_673,
        din56 => network_weights_weig_674,
        din57 => network_weights_weig_675,
        din58 => network_weights_weig_676,
        din59 => network_weights_weig_677,
        din60 => network_weights_weig_678,
        din61 => network_weights_weig_679,
        din62 => network_weights_weig_680,
        din63 => network_weights_weig_681,
        din64 => network_weights_weig_682,
        din65 => network_weights_weig_683,
        din66 => network_weights_weig_684,
        din67 => network_weights_weig_685,
        din68 => network_weights_weig_686,
        din69 => network_weights_weig_687,
        din70 => network_weights_weig_688,
        din71 => network_weights_weig_689,
        din72 => network_weights_weig_690,
        din73 => network_weights_weig_691,
        din74 => network_weights_weig_692,
        din75 => network_weights_weig_693,
        din76 => network_weights_weig_694,
        din77 => network_weights_weig_695,
        din78 => network_weights_weig_696,
        din79 => network_weights_weig_697,
        din80 => network_weights_weig_698,
        din81 => network_weights_weig_699,
        din82 => network_weights_weig_700,
        din83 => network_weights_weig_701,
        din84 => network_weights_weig_702,
        din85 => network_weights_weig_703,
        din86 => network_weights_weig_704,
        din87 => network_weights_weig_705,
        din88 => network_weights_weig_706,
        din89 => network_weights_weig_707,
        din90 => network_weights_weig_708,
        din91 => network_weights_weig_709,
        din92 => network_weights_weig_710,
        din93 => network_weights_weig_711,
        din94 => network_weights_weig_712,
        din95 => network_weights_weig_713,
        din96 => network_weights_weig_714,
        din97 => network_weights_weig_715,
        din98 => network_weights_weig_716,
        din99 => network_weights_weig_717,
        din100 => network_weights_weig_718,
        din101 => network_weights_weig_719,
        din102 => network_weights_weig_720,
        din103 => network_weights_weig_721,
        din104 => network_weights_weig_722,
        din105 => network_weights_weig_723,
        din106 => network_weights_weig_724,
        din107 => network_weights_weig_725,
        din108 => network_weights_weig_726,
        din109 => network_weights_weig_727,
        din110 => network_weights_weig_728,
        din111 => network_weights_weig_729,
        din112 => network_weights_weig_730,
        din113 => network_weights_weig_731,
        din114 => network_weights_weig_732,
        din115 => network_weights_weig_733,
        din116 => network_weights_weig_734,
        din117 => network_weights_weig_735,
        din118 => network_weights_weig_736,
        din119 => network_weights_weig_737,
        din120 => network_weights_weig_738,
        din121 => network_weights_weig_739,
        din122 => network_weights_weig_740,
        din123 => network_weights_weig_741,
        din124 => network_weights_weig_742,
        din125 => network_weights_weig_743,
        din126 => network_weights_weig_744,
        din127 => network_weights_weig_745,
        din128 => tmp_1_fu_1730_p129,
        dout => tmp_1_fu_1730_p130);

    network_top_mux_3eOg_U40 : component network_top_mux_3eOg
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 8,
        din5_WIDTH => 8,
        din6_WIDTH => 8,
        din7_WIDTH => 8,
        din8_WIDTH => 8,
        din9_WIDTH => 8,
        din10_WIDTH => 8,
        din11_WIDTH => 8,
        din12_WIDTH => 8,
        din13_WIDTH => 8,
        din14_WIDTH => 8,
        din15_WIDTH => 8,
        din16_WIDTH => 8,
        din17_WIDTH => 8,
        din18_WIDTH => 8,
        din19_WIDTH => 8,
        din20_WIDTH => 8,
        din21_WIDTH => 8,
        din22_WIDTH => 8,
        din23_WIDTH => 8,
        din24_WIDTH => 8,
        din25_WIDTH => 8,
        din26_WIDTH => 8,
        din27_WIDTH => 8,
        din28_WIDTH => 8,
        din29_WIDTH => 8,
        din30_WIDTH => 8,
        din31_WIDTH => 8,
        din32_WIDTH => 6,
        dout_WIDTH => 8)
    port map (
        din0 => network_weights_weig_746,
        din1 => network_weights_weig_747,
        din2 => network_weights_weig_748,
        din3 => network_weights_weig_749,
        din4 => network_weights_weig_750,
        din5 => network_weights_weig_751,
        din6 => network_weights_weig_752,
        din7 => network_weights_weig_753,
        din8 => network_weights_weig_754,
        din9 => network_weights_weig_755,
        din10 => network_weights_weig_756,
        din11 => network_weights_weig_757,
        din12 => network_weights_weig_758,
        din13 => network_weights_weig_759,
        din14 => network_weights_weig_760,
        din15 => network_weights_weig_761,
        din16 => network_weights_weig_762,
        din17 => network_weights_weig_763,
        din18 => network_weights_weig_764,
        din19 => network_weights_weig_765,
        din20 => network_weights_weig_766,
        din21 => network_weights_weig_767,
        din22 => network_weights_weig_768,
        din23 => network_weights_weig_769,
        din24 => network_weights_weig_770,
        din25 => network_weights_weig_771,
        din26 => network_weights_weig_772,
        din27 => network_weights_weig_773,
        din28 => network_weights_weig_774,
        din29 => network_weights_weig_775,
        din30 => network_weights_weig_776,
        din31 => network_weights_weig_777,
        din32 => tmp_2_fu_2012_p33,
        dout => tmp_2_fu_2012_p34);

    network_top_mux_4g8j_U41 : component network_top_mux_4g8j
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 8,
        din4_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => network_weights_weig_778,
        din1 => network_weights_weig_779,
        din2 => network_weights_weig_780,
        din3 => network_weights_weig_781,
        din4 => tmp_3_fu_2086_p5,
        dout => tmp_3_fu_2086_p6);




    ap_ready <= ap_const_logic_1;
    ap_return <= 
        select_ln9_2_fu_2156_p3 when (or_ln9_2_fu_2164_p2(0) = '1') else 
        ap_const_lv8_0;
    icmp_ln9_1_fu_2110_p2 <= "1" when (trunc_ln9_fu_2100_p1 = ap_const_lv2_2) else "0";
    icmp_ln9_2_fu_2116_p2 <= "1" when (trunc_ln9_fu_2100_p1 = ap_const_lv2_1) else "0";
    icmp_ln9_3_fu_2122_p2 <= "1" when (trunc_ln9_fu_2100_p1 = ap_const_lv2_0) else "0";
    icmp_ln9_fu_2104_p2 <= "1" when (trunc_ln9_fu_2100_p1 = ap_const_lv2_3) else "0";
    or_ln9_1_fu_2150_p2 <= (icmp_ln9_fu_2104_p2 or icmp_ln9_1_fu_2110_p2);
    or_ln9_2_fu_2164_p2 <= (or_ln9_fu_2136_p2 or or_ln9_1_fu_2150_p2);
    or_ln9_fu_2136_p2 <= (icmp_ln9_3_fu_2122_p2 or icmp_ln9_2_fu_2116_p2);
    select_ln9_1_fu_2142_p3 <= 
        tmp_2_fu_2012_p34 when (icmp_ln9_1_fu_2110_p2(0) = '1') else 
        tmp_3_fu_2086_p6;
    select_ln9_2_fu_2156_p3 <= 
        select_ln9_fu_2128_p3 when (or_ln9_fu_2136_p2(0) = '1') else 
        select_ln9_1_fu_2142_p3;
    select_ln9_fu_2128_p3 <= 
        tmp_fu_1640_p34 when (icmp_ln9_3_fu_2122_p2(0) = '1') else 
        tmp_1_fu_1730_p130;
    tmp_1_fu_1730_p129 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_1718_p3),8));
    tmp_2_fu_2012_p33 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_2000_p3),6));
    tmp_3_fu_2086_p5 <= index_1(2 - 1 downto 0);
    tmp_4_fu_1628_p3 <= (trunc_ln12_fu_1620_p1 & trunc_ln12_1_fu_1624_p1);
    tmp_5_fu_1718_p3 <= (trunc_ln15_fu_1710_p1 & trunc_ln15_1_fu_1714_p1);
    tmp_6_fu_2000_p3 <= (trunc_ln18_fu_1992_p1 & trunc_ln18_1_fu_1996_p1);
    tmp_fu_1640_p33 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_1628_p3),6));
    trunc_ln12_1_fu_1624_p1 <= index_1(1 - 1 downto 0);
    trunc_ln12_fu_1620_p1 <= index_0(4 - 1 downto 0);
    trunc_ln15_1_fu_1714_p1 <= index_1(4 - 1 downto 0);
    trunc_ln15_fu_1710_p1 <= index_0(3 - 1 downto 0);
    trunc_ln18_1_fu_1996_p1 <= index_1(3 - 1 downto 0);
    trunc_ln18_fu_1992_p1 <= index_0(2 - 1 downto 0);
    trunc_ln9_fu_2100_p1 <= layer(2 - 1 downto 0);
end behav;
