// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getBias (
        ap_ready,
        network_weights_bias,
        network_weights_bias_33,
        network_weights_bias_34,
        network_weights_bias_35,
        network_weights_bias_36,
        network_weights_bias_37,
        network_weights_bias_38,
        network_weights_bias_39,
        network_weights_bias_40,
        network_weights_bias_41,
        network_weights_bias_42,
        network_weights_bias_43,
        network_weights_bias_44,
        network_weights_bias_45,
        network_weights_bias_46,
        network_weights_bias_47,
        network_weights_bias_48,
        layer,
        index,
        ap_return
);


output   ap_ready;
input  [31:0] network_weights_bias;
input  [31:0] network_weights_bias_33;
input  [31:0] network_weights_bias_34;
input  [31:0] network_weights_bias_35;
input  [31:0] network_weights_bias_36;
input  [31:0] network_weights_bias_37;
input  [31:0] network_weights_bias_38;
input  [31:0] network_weights_bias_39;
input  [31:0] network_weights_bias_40;
input  [31:0] network_weights_bias_41;
input  [31:0] network_weights_bias_42;
input  [31:0] network_weights_bias_43;
input  [31:0] network_weights_bias_44;
input  [31:0] network_weights_bias_45;
input  [31:0] network_weights_bias_46;
input  [31:0] network_weights_bias_47;
input  [31:0] network_weights_bias_48;
input  [3:0] layer;
input  [3:0] index;
output  [31:0] ap_return;

wire   [2:0] trunc_ln29_fu_166_p1;
wire   [1:0] trunc_ln26_fu_214_p1;
wire   [0:0] icmp_ln26_2_fu_230_p2;
wire   [31:0] tmp_fu_170_p10;
wire   [31:0] tmp_3_fu_192_p10;
wire   [0:0] icmp_ln26_1_fu_224_p2;
wire   [0:0] icmp_ln26_fu_218_p2;
wire   [0:0] or_ln26_fu_244_p2;
wire   [31:0] select_ln26_fu_236_p3;
wire   [31:0] select_ln26_1_fu_250_p3;

network_top_mux_8bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
network_top_mux_8bkb_U1(
    .din0(network_weights_bias),
    .din1(network_weights_bias_33),
    .din2(network_weights_bias_34),
    .din3(network_weights_bias_35),
    .din4(network_weights_bias_36),
    .din5(network_weights_bias_37),
    .din6(network_weights_bias_38),
    .din7(network_weights_bias_39),
    .din8(trunc_ln29_fu_166_p1),
    .dout(tmp_fu_170_p10)
);

network_top_mux_8bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
network_top_mux_8bkb_U2(
    .din0(network_weights_bias_40),
    .din1(network_weights_bias_41),
    .din2(network_weights_bias_42),
    .din3(network_weights_bias_43),
    .din4(network_weights_bias_44),
    .din5(network_weights_bias_45),
    .din6(network_weights_bias_46),
    .din7(network_weights_bias_47),
    .din8(trunc_ln29_fu_166_p1),
    .dout(tmp_3_fu_192_p10)
);

assign ap_ready = 1'b1;

assign ap_return = ((or_ln26_fu_244_p2[0:0] === 1'b1) ? select_ln26_fu_236_p3 : select_ln26_1_fu_250_p3);

assign icmp_ln26_1_fu_224_p2 = ((trunc_ln26_fu_214_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln26_2_fu_230_p2 = ((trunc_ln26_fu_214_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_218_p2 = ((trunc_ln26_fu_214_p1 == 2'd2) ? 1'b1 : 1'b0);

assign or_ln26_fu_244_p2 = (icmp_ln26_2_fu_230_p2 | icmp_ln26_1_fu_224_p2);

assign select_ln26_1_fu_250_p3 = ((icmp_ln26_fu_218_p2[0:0] === 1'b1) ? network_weights_bias_48 : 32'd0);

assign select_ln26_fu_236_p3 = ((icmp_ln26_2_fu_230_p2[0:0] === 1'b1) ? tmp_fu_170_p10 : tmp_3_fu_192_p10);

assign trunc_ln26_fu_214_p1 = layer[1:0];

assign trunc_ln29_fu_166_p1 = index[2:0];

endmodule //getBias
