// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "getWeight.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic getWeight::ap_const_logic_1 = sc_dt::Log_1;
const bool getWeight::ap_const_boolean_1 = true;
const sc_lv<2> getWeight::ap_const_lv2_2 = "10";
const sc_lv<2> getWeight::ap_const_lv2_1 = "1";
const sc_lv<2> getWeight::ap_const_lv2_0 = "00";
const sc_lv<8> getWeight::ap_const_lv8_0 = "00000000";
const sc_lv<1> getWeight::ap_const_lv1_0 = "0";
const sc_logic getWeight::ap_const_logic_0 = sc_dt::Log_0;

getWeight::getWeight(sc_module_name name) : sc_module(name), mVcdFile(0) {
    network_top_mux_1cud_U23 = new network_top_mux_1cud<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,5,8>("network_top_mux_1cud_U23");
    network_top_mux_1cud_U23->din0(network_weights_weig);
    network_top_mux_1cud_U23->din1(network_weights_weig_175);
    network_top_mux_1cud_U23->din2(network_weights_weig_176);
    network_top_mux_1cud_U23->din3(network_weights_weig_177);
    network_top_mux_1cud_U23->din4(network_weights_weig_178);
    network_top_mux_1cud_U23->din5(network_weights_weig_179);
    network_top_mux_1cud_U23->din6(network_weights_weig_180);
    network_top_mux_1cud_U23->din7(network_weights_weig_181);
    network_top_mux_1cud_U23->din8(network_weights_weig_182);
    network_top_mux_1cud_U23->din9(network_weights_weig_183);
    network_top_mux_1cud_U23->din10(network_weights_weig_184);
    network_top_mux_1cud_U23->din11(network_weights_weig_185);
    network_top_mux_1cud_U23->din12(network_weights_weig_186);
    network_top_mux_1cud_U23->din13(network_weights_weig_187);
    network_top_mux_1cud_U23->din14(network_weights_weig_188);
    network_top_mux_1cud_U23->din15(network_weights_weig_189);
    network_top_mux_1cud_U23->din16(tmp_fu_770_p17);
    network_top_mux_1cud_U23->dout(tmp_fu_770_p18);
    network_top_mux_6dEe_U24 = new network_top_mux_6dEe<1,1,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,7,8>("network_top_mux_6dEe_U24");
    network_top_mux_6dEe_U24->din0(network_weights_weig_190);
    network_top_mux_6dEe_U24->din1(network_weights_weig_191);
    network_top_mux_6dEe_U24->din2(network_weights_weig_192);
    network_top_mux_6dEe_U24->din3(network_weights_weig_193);
    network_top_mux_6dEe_U24->din4(network_weights_weig_194);
    network_top_mux_6dEe_U24->din5(network_weights_weig_195);
    network_top_mux_6dEe_U24->din6(network_weights_weig_196);
    network_top_mux_6dEe_U24->din7(network_weights_weig_197);
    network_top_mux_6dEe_U24->din8(network_weights_weig_198);
    network_top_mux_6dEe_U24->din9(network_weights_weig_199);
    network_top_mux_6dEe_U24->din10(network_weights_weig_200);
    network_top_mux_6dEe_U24->din11(network_weights_weig_201);
    network_top_mux_6dEe_U24->din12(network_weights_weig_202);
    network_top_mux_6dEe_U24->din13(network_weights_weig_203);
    network_top_mux_6dEe_U24->din14(network_weights_weig_204);
    network_top_mux_6dEe_U24->din15(network_weights_weig_205);
    network_top_mux_6dEe_U24->din16(network_weights_weig_206);
    network_top_mux_6dEe_U24->din17(network_weights_weig_207);
    network_top_mux_6dEe_U24->din18(network_weights_weig_208);
    network_top_mux_6dEe_U24->din19(network_weights_weig_209);
    network_top_mux_6dEe_U24->din20(network_weights_weig_210);
    network_top_mux_6dEe_U24->din21(network_weights_weig_211);
    network_top_mux_6dEe_U24->din22(network_weights_weig_212);
    network_top_mux_6dEe_U24->din23(network_weights_weig_213);
    network_top_mux_6dEe_U24->din24(network_weights_weig_214);
    network_top_mux_6dEe_U24->din25(network_weights_weig_215);
    network_top_mux_6dEe_U24->din26(network_weights_weig_216);
    network_top_mux_6dEe_U24->din27(network_weights_weig_217);
    network_top_mux_6dEe_U24->din28(network_weights_weig_218);
    network_top_mux_6dEe_U24->din29(network_weights_weig_219);
    network_top_mux_6dEe_U24->din30(network_weights_weig_220);
    network_top_mux_6dEe_U24->din31(network_weights_weig_221);
    network_top_mux_6dEe_U24->din32(network_weights_weig_222);
    network_top_mux_6dEe_U24->din33(network_weights_weig_223);
    network_top_mux_6dEe_U24->din34(network_weights_weig_224);
    network_top_mux_6dEe_U24->din35(network_weights_weig_225);
    network_top_mux_6dEe_U24->din36(network_weights_weig_226);
    network_top_mux_6dEe_U24->din37(network_weights_weig_227);
    network_top_mux_6dEe_U24->din38(network_weights_weig_228);
    network_top_mux_6dEe_U24->din39(network_weights_weig_229);
    network_top_mux_6dEe_U24->din40(network_weights_weig_230);
    network_top_mux_6dEe_U24->din41(network_weights_weig_231);
    network_top_mux_6dEe_U24->din42(network_weights_weig_232);
    network_top_mux_6dEe_U24->din43(network_weights_weig_233);
    network_top_mux_6dEe_U24->din44(network_weights_weig_234);
    network_top_mux_6dEe_U24->din45(network_weights_weig_235);
    network_top_mux_6dEe_U24->din46(network_weights_weig_236);
    network_top_mux_6dEe_U24->din47(network_weights_weig_237);
    network_top_mux_6dEe_U24->din48(network_weights_weig_238);
    network_top_mux_6dEe_U24->din49(network_weights_weig_239);
    network_top_mux_6dEe_U24->din50(network_weights_weig_240);
    network_top_mux_6dEe_U24->din51(network_weights_weig_241);
    network_top_mux_6dEe_U24->din52(network_weights_weig_242);
    network_top_mux_6dEe_U24->din53(network_weights_weig_243);
    network_top_mux_6dEe_U24->din54(network_weights_weig_244);
    network_top_mux_6dEe_U24->din55(network_weights_weig_245);
    network_top_mux_6dEe_U24->din56(network_weights_weig_246);
    network_top_mux_6dEe_U24->din57(network_weights_weig_247);
    network_top_mux_6dEe_U24->din58(network_weights_weig_248);
    network_top_mux_6dEe_U24->din59(network_weights_weig_249);
    network_top_mux_6dEe_U24->din60(network_weights_weig_250);
    network_top_mux_6dEe_U24->din61(network_weights_weig_251);
    network_top_mux_6dEe_U24->din62(network_weights_weig_252);
    network_top_mux_6dEe_U24->din63(network_weights_weig_253);
    network_top_mux_6dEe_U24->din64(tmp_1_fu_824_p65);
    network_top_mux_6dEe_U24->dout(tmp_1_fu_824_p66);
    network_top_mux_8eOg_U25 = new network_top_mux_8eOg<1,1,8,8,8,8,8,8,8,8,3,8>("network_top_mux_8eOg_U25");
    network_top_mux_8eOg_U25->din0(network_weights_weig_254);
    network_top_mux_8eOg_U25->din1(network_weights_weig_255);
    network_top_mux_8eOg_U25->din2(network_weights_weig_256);
    network_top_mux_8eOg_U25->din3(network_weights_weig_257);
    network_top_mux_8eOg_U25->din4(network_weights_weig_258);
    network_top_mux_8eOg_U25->din5(network_weights_weig_259);
    network_top_mux_8eOg_U25->din6(network_weights_weig_260);
    network_top_mux_8eOg_U25->din7(network_weights_weig_261);
    network_top_mux_8eOg_U25->din8(trunc_ln14_fu_808_p1);
    network_top_mux_8eOg_U25->dout(tmp_2_fu_958_p10);

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( or_ln8_fu_1010_p2 );
    sensitive << ( select_ln8_fu_1002_p3 );
    sensitive << ( select_ln8_1_fu_1016_p3 );

    SC_METHOD(thread_icmp_ln8_1_fu_990_p2);
    sensitive << ( trunc_ln8_fu_980_p1 );

    SC_METHOD(thread_icmp_ln8_2_fu_996_p2);
    sensitive << ( trunc_ln8_fu_980_p1 );

    SC_METHOD(thread_icmp_ln8_fu_984_p2);
    sensitive << ( trunc_ln8_fu_980_p1 );
    sensitive << ( or_ln8_fu_1010_p2 );

    SC_METHOD(thread_or_ln8_fu_1010_p2);
    sensitive << ( icmp_ln8_2_fu_996_p2 );
    sensitive << ( icmp_ln8_1_fu_990_p2 );

    SC_METHOD(thread_select_ln8_1_fu_1016_p3);
    sensitive << ( icmp_ln8_fu_984_p2 );
    sensitive << ( tmp_2_fu_958_p10 );

    SC_METHOD(thread_select_ln8_fu_1002_p3);
    sensitive << ( icmp_ln8_2_fu_996_p2 );
    sensitive << ( tmp_fu_770_p18 );
    sensitive << ( tmp_1_fu_824_p66 );

    SC_METHOD(thread_tmp_1_fu_824_p65);
    sensitive << ( tmp_4_fu_812_p3 );

    SC_METHOD(thread_tmp_3_fu_758_p3);
    sensitive << ( trunc_ln11_fu_750_p1 );
    sensitive << ( trunc_ln11_1_fu_754_p1 );

    SC_METHOD(thread_tmp_4_fu_812_p3);
    sensitive << ( trunc_ln11_fu_750_p1 );
    sensitive << ( trunc_ln14_fu_808_p1 );

    SC_METHOD(thread_tmp_fu_770_p17);
    sensitive << ( tmp_3_fu_758_p3 );

    SC_METHOD(thread_trunc_ln11_1_fu_754_p1);
    sensitive << ( index_1 );

    SC_METHOD(thread_trunc_ln11_fu_750_p1);
    sensitive << ( index_0 );

    SC_METHOD(thread_trunc_ln14_fu_808_p1);
    sensitive << ( index_1 );

    SC_METHOD(thread_trunc_ln8_fu_980_p1);
    sensitive << ( layer );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "getWeight_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, network_weights_weig, "(port)network_weights_weig");
    sc_trace(mVcdFile, network_weights_weig_175, "(port)network_weights_weig_175");
    sc_trace(mVcdFile, network_weights_weig_176, "(port)network_weights_weig_176");
    sc_trace(mVcdFile, network_weights_weig_177, "(port)network_weights_weig_177");
    sc_trace(mVcdFile, network_weights_weig_178, "(port)network_weights_weig_178");
    sc_trace(mVcdFile, network_weights_weig_179, "(port)network_weights_weig_179");
    sc_trace(mVcdFile, network_weights_weig_180, "(port)network_weights_weig_180");
    sc_trace(mVcdFile, network_weights_weig_181, "(port)network_weights_weig_181");
    sc_trace(mVcdFile, network_weights_weig_182, "(port)network_weights_weig_182");
    sc_trace(mVcdFile, network_weights_weig_183, "(port)network_weights_weig_183");
    sc_trace(mVcdFile, network_weights_weig_184, "(port)network_weights_weig_184");
    sc_trace(mVcdFile, network_weights_weig_185, "(port)network_weights_weig_185");
    sc_trace(mVcdFile, network_weights_weig_186, "(port)network_weights_weig_186");
    sc_trace(mVcdFile, network_weights_weig_187, "(port)network_weights_weig_187");
    sc_trace(mVcdFile, network_weights_weig_188, "(port)network_weights_weig_188");
    sc_trace(mVcdFile, network_weights_weig_189, "(port)network_weights_weig_189");
    sc_trace(mVcdFile, network_weights_weig_190, "(port)network_weights_weig_190");
    sc_trace(mVcdFile, network_weights_weig_191, "(port)network_weights_weig_191");
    sc_trace(mVcdFile, network_weights_weig_192, "(port)network_weights_weig_192");
    sc_trace(mVcdFile, network_weights_weig_193, "(port)network_weights_weig_193");
    sc_trace(mVcdFile, network_weights_weig_194, "(port)network_weights_weig_194");
    sc_trace(mVcdFile, network_weights_weig_195, "(port)network_weights_weig_195");
    sc_trace(mVcdFile, network_weights_weig_196, "(port)network_weights_weig_196");
    sc_trace(mVcdFile, network_weights_weig_197, "(port)network_weights_weig_197");
    sc_trace(mVcdFile, network_weights_weig_198, "(port)network_weights_weig_198");
    sc_trace(mVcdFile, network_weights_weig_199, "(port)network_weights_weig_199");
    sc_trace(mVcdFile, network_weights_weig_200, "(port)network_weights_weig_200");
    sc_trace(mVcdFile, network_weights_weig_201, "(port)network_weights_weig_201");
    sc_trace(mVcdFile, network_weights_weig_202, "(port)network_weights_weig_202");
    sc_trace(mVcdFile, network_weights_weig_203, "(port)network_weights_weig_203");
    sc_trace(mVcdFile, network_weights_weig_204, "(port)network_weights_weig_204");
    sc_trace(mVcdFile, network_weights_weig_205, "(port)network_weights_weig_205");
    sc_trace(mVcdFile, network_weights_weig_206, "(port)network_weights_weig_206");
    sc_trace(mVcdFile, network_weights_weig_207, "(port)network_weights_weig_207");
    sc_trace(mVcdFile, network_weights_weig_208, "(port)network_weights_weig_208");
    sc_trace(mVcdFile, network_weights_weig_209, "(port)network_weights_weig_209");
    sc_trace(mVcdFile, network_weights_weig_210, "(port)network_weights_weig_210");
    sc_trace(mVcdFile, network_weights_weig_211, "(port)network_weights_weig_211");
    sc_trace(mVcdFile, network_weights_weig_212, "(port)network_weights_weig_212");
    sc_trace(mVcdFile, network_weights_weig_213, "(port)network_weights_weig_213");
    sc_trace(mVcdFile, network_weights_weig_214, "(port)network_weights_weig_214");
    sc_trace(mVcdFile, network_weights_weig_215, "(port)network_weights_weig_215");
    sc_trace(mVcdFile, network_weights_weig_216, "(port)network_weights_weig_216");
    sc_trace(mVcdFile, network_weights_weig_217, "(port)network_weights_weig_217");
    sc_trace(mVcdFile, network_weights_weig_218, "(port)network_weights_weig_218");
    sc_trace(mVcdFile, network_weights_weig_219, "(port)network_weights_weig_219");
    sc_trace(mVcdFile, network_weights_weig_220, "(port)network_weights_weig_220");
    sc_trace(mVcdFile, network_weights_weig_221, "(port)network_weights_weig_221");
    sc_trace(mVcdFile, network_weights_weig_222, "(port)network_weights_weig_222");
    sc_trace(mVcdFile, network_weights_weig_223, "(port)network_weights_weig_223");
    sc_trace(mVcdFile, network_weights_weig_224, "(port)network_weights_weig_224");
    sc_trace(mVcdFile, network_weights_weig_225, "(port)network_weights_weig_225");
    sc_trace(mVcdFile, network_weights_weig_226, "(port)network_weights_weig_226");
    sc_trace(mVcdFile, network_weights_weig_227, "(port)network_weights_weig_227");
    sc_trace(mVcdFile, network_weights_weig_228, "(port)network_weights_weig_228");
    sc_trace(mVcdFile, network_weights_weig_229, "(port)network_weights_weig_229");
    sc_trace(mVcdFile, network_weights_weig_230, "(port)network_weights_weig_230");
    sc_trace(mVcdFile, network_weights_weig_231, "(port)network_weights_weig_231");
    sc_trace(mVcdFile, network_weights_weig_232, "(port)network_weights_weig_232");
    sc_trace(mVcdFile, network_weights_weig_233, "(port)network_weights_weig_233");
    sc_trace(mVcdFile, network_weights_weig_234, "(port)network_weights_weig_234");
    sc_trace(mVcdFile, network_weights_weig_235, "(port)network_weights_weig_235");
    sc_trace(mVcdFile, network_weights_weig_236, "(port)network_weights_weig_236");
    sc_trace(mVcdFile, network_weights_weig_237, "(port)network_weights_weig_237");
    sc_trace(mVcdFile, network_weights_weig_238, "(port)network_weights_weig_238");
    sc_trace(mVcdFile, network_weights_weig_239, "(port)network_weights_weig_239");
    sc_trace(mVcdFile, network_weights_weig_240, "(port)network_weights_weig_240");
    sc_trace(mVcdFile, network_weights_weig_241, "(port)network_weights_weig_241");
    sc_trace(mVcdFile, network_weights_weig_242, "(port)network_weights_weig_242");
    sc_trace(mVcdFile, network_weights_weig_243, "(port)network_weights_weig_243");
    sc_trace(mVcdFile, network_weights_weig_244, "(port)network_weights_weig_244");
    sc_trace(mVcdFile, network_weights_weig_245, "(port)network_weights_weig_245");
    sc_trace(mVcdFile, network_weights_weig_246, "(port)network_weights_weig_246");
    sc_trace(mVcdFile, network_weights_weig_247, "(port)network_weights_weig_247");
    sc_trace(mVcdFile, network_weights_weig_248, "(port)network_weights_weig_248");
    sc_trace(mVcdFile, network_weights_weig_249, "(port)network_weights_weig_249");
    sc_trace(mVcdFile, network_weights_weig_250, "(port)network_weights_weig_250");
    sc_trace(mVcdFile, network_weights_weig_251, "(port)network_weights_weig_251");
    sc_trace(mVcdFile, network_weights_weig_252, "(port)network_weights_weig_252");
    sc_trace(mVcdFile, network_weights_weig_253, "(port)network_weights_weig_253");
    sc_trace(mVcdFile, network_weights_weig_254, "(port)network_weights_weig_254");
    sc_trace(mVcdFile, network_weights_weig_255, "(port)network_weights_weig_255");
    sc_trace(mVcdFile, network_weights_weig_256, "(port)network_weights_weig_256");
    sc_trace(mVcdFile, network_weights_weig_257, "(port)network_weights_weig_257");
    sc_trace(mVcdFile, network_weights_weig_258, "(port)network_weights_weig_258");
    sc_trace(mVcdFile, network_weights_weig_259, "(port)network_weights_weig_259");
    sc_trace(mVcdFile, network_weights_weig_260, "(port)network_weights_weig_260");
    sc_trace(mVcdFile, network_weights_weig_261, "(port)network_weights_weig_261");
    sc_trace(mVcdFile, layer, "(port)layer");
    sc_trace(mVcdFile, index_0, "(port)index_0");
    sc_trace(mVcdFile, index_1, "(port)index_1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, trunc_ln11_fu_750_p1, "trunc_ln11_fu_750_p1");
    sc_trace(mVcdFile, trunc_ln11_1_fu_754_p1, "trunc_ln11_1_fu_754_p1");
    sc_trace(mVcdFile, tmp_3_fu_758_p3, "tmp_3_fu_758_p3");
    sc_trace(mVcdFile, tmp_fu_770_p17, "tmp_fu_770_p17");
    sc_trace(mVcdFile, trunc_ln14_fu_808_p1, "trunc_ln14_fu_808_p1");
    sc_trace(mVcdFile, tmp_4_fu_812_p3, "tmp_4_fu_812_p3");
    sc_trace(mVcdFile, tmp_1_fu_824_p65, "tmp_1_fu_824_p65");
    sc_trace(mVcdFile, trunc_ln8_fu_980_p1, "trunc_ln8_fu_980_p1");
    sc_trace(mVcdFile, icmp_ln8_2_fu_996_p2, "icmp_ln8_2_fu_996_p2");
    sc_trace(mVcdFile, tmp_fu_770_p18, "tmp_fu_770_p18");
    sc_trace(mVcdFile, tmp_1_fu_824_p66, "tmp_1_fu_824_p66");
    sc_trace(mVcdFile, icmp_ln8_1_fu_990_p2, "icmp_ln8_1_fu_990_p2");
    sc_trace(mVcdFile, icmp_ln8_fu_984_p2, "icmp_ln8_fu_984_p2");
    sc_trace(mVcdFile, tmp_2_fu_958_p10, "tmp_2_fu_958_p10");
    sc_trace(mVcdFile, or_ln8_fu_1010_p2, "or_ln8_fu_1010_p2");
    sc_trace(mVcdFile, select_ln8_fu_1002_p3, "select_ln8_fu_1002_p3");
    sc_trace(mVcdFile, select_ln8_1_fu_1016_p3, "select_ln8_1_fu_1016_p3");
#endif

    }
}

getWeight::~getWeight() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete network_top_mux_1cud_U23;
    delete network_top_mux_6dEe_U24;
    delete network_top_mux_8eOg_U25;
}

void getWeight::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void getWeight::thread_ap_return() {
    ap_return = (!or_ln8_fu_1010_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln8_fu_1010_p2.read()[0].to_bool())? select_ln8_fu_1002_p3.read(): select_ln8_1_fu_1016_p3.read());
}

void getWeight::thread_icmp_ln8_1_fu_990_p2() {
    icmp_ln8_1_fu_990_p2 = (!trunc_ln8_fu_980_p1.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln8_fu_980_p1.read() == ap_const_lv2_1);
}

void getWeight::thread_icmp_ln8_2_fu_996_p2() {
    icmp_ln8_2_fu_996_p2 = (!trunc_ln8_fu_980_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln8_fu_980_p1.read() == ap_const_lv2_0);
}

void getWeight::thread_icmp_ln8_fu_984_p2() {
    icmp_ln8_fu_984_p2 = (!trunc_ln8_fu_980_p1.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln8_fu_980_p1.read() == ap_const_lv2_2);
}

void getWeight::thread_or_ln8_fu_1010_p2() {
    or_ln8_fu_1010_p2 = (icmp_ln8_2_fu_996_p2.read() | icmp_ln8_1_fu_990_p2.read());
}

void getWeight::thread_select_ln8_1_fu_1016_p3() {
    select_ln8_1_fu_1016_p3 = (!icmp_ln8_fu_984_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln8_fu_984_p2.read()[0].to_bool())? tmp_2_fu_958_p10.read(): ap_const_lv8_0);
}

void getWeight::thread_select_ln8_fu_1002_p3() {
    select_ln8_fu_1002_p3 = (!icmp_ln8_2_fu_996_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln8_2_fu_996_p2.read()[0].to_bool())? tmp_fu_770_p18.read(): tmp_1_fu_824_p66.read());
}

void getWeight::thread_tmp_1_fu_824_p65() {
    tmp_1_fu_824_p65 = esl_zext<7,6>(tmp_4_fu_812_p3.read());
}

void getWeight::thread_tmp_3_fu_758_p3() {
    tmp_3_fu_758_p3 = esl_concat<3,1>(trunc_ln11_fu_750_p1.read(), trunc_ln11_1_fu_754_p1.read());
}

void getWeight::thread_tmp_4_fu_812_p3() {
    tmp_4_fu_812_p3 = esl_concat<3,3>(trunc_ln11_fu_750_p1.read(), trunc_ln14_fu_808_p1.read());
}

void getWeight::thread_tmp_fu_770_p17() {
    tmp_fu_770_p17 = esl_zext<5,4>(tmp_3_fu_758_p3.read());
}

void getWeight::thread_trunc_ln11_1_fu_754_p1() {
    trunc_ln11_1_fu_754_p1 = index_1.read().range(1-1, 0);
}

void getWeight::thread_trunc_ln11_fu_750_p1() {
    trunc_ln11_fu_750_p1 = index_0.read().range(3-1, 0);
}

void getWeight::thread_trunc_ln14_fu_808_p1() {
    trunc_ln14_fu_808_p1 = index_1.read().range(3-1, 0);
}

void getWeight::thread_trunc_ln8_fu_980_p1() {
    trunc_ln8_fu_980_p1 = layer.read().range(2-1, 0);
}

}

